/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAlertRulesResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAlertRulesResponseInner{}

// ListAlertRulesResponseInner One metric-threshold alert rule.
type ListAlertRulesResponseInner struct {
	// Stable opaque alert-rule id.
	Id string `json:"id"`
	// Human label for the rule.
	Name string `json:"name"`
	// Id of the metric the rule evaluates. Immutable after create.
	MetricId string `json:"metricId"`
	// Display name of the bound metric, or `null` if the metric no longer exists.
	MetricName NullableString `json:"metricName"`
	// What the rule watches for. `normal` compares the metric's own value — against `threshold` via `comparator`, or against the [`rangeMin`, `rangeMax`] corridor it must stay inside. `anomaly` compares it against ITS OWN seasonal baseline in sigmas, which is the same fit a chart draws as the band. `outliers` compares each `by()` group against its peers in the same bucket, so it needs a grouped metric. `no_data` fires when the metric records nothing at all for `noDataMinutes` — a count of zero is not silence, and the two are distinguished by the reader's presence columns. `composite` is a boolean over OTHER rules' current state and watches no metric of its own.
	Kind string `json:"kind"`
	// How the metric value is compared to the threshold (gt/gte/lt/lte). Read only by a `normal` rule with no range set.
	Comparator string `json:"comparator"`
	// Threshold the metric value is compared against. Read only by a `normal` rule with no range set.
	Threshold float32 `json:"threshold"`
	// Lower edge of the corridor a `normal` rule must stay inside; `null` if the rule is judged by comparator and threshold.
	RangeMin NullableFloat32 `json:"rangeMin"`
	// Upper edge of the corridor a `normal` rule must stay inside; `null` if the rule is judged by comparator and threshold.
	RangeMax NullableFloat32 `json:"rangeMax"`
	// How far from normal is too far, for `anomaly` and `outliers`, in sigma-equivalents. `null` takes the default of 3, which is also the width of the band a chart draws.
	Sigma NullableFloat32 `json:"sigma"`
	// Which side of the baseline an `anomaly` or `outliers` rule watches. `null` means either.
	Direction NullableString `json:"direction"`
	// Whether the rule is judged by ACCUMULATED departure rather than bucket by bucket. `anomaly` and `outliers` only.
	Sustained bool `json:"sustained"`
	// The milder bound, in the same unit the kind judges in. `null` means the rule has one level.
	WarnThreshold NullableFloat32 `json:"warnThreshold"`
	// What the metric must get back to before a live alert closes. `null` means no hysteresis — the firing bound clears it.
	RecoveryThreshold NullableFloat32 `json:"recoveryThreshold"`
	// Whether the rule fires one alert per `by()` group rather than one for the whole metric.
	GroupAlerts bool `json:"groupAlerts"`
	// How many groups this rule may alert on at once. `null` takes the shipped cap of 10.
	MaxGroups NullableInt32 `json:"maxGroups"`
	// How long the silence must last for a `no_data` rule. `null` on every other kind.
	NoDataMinutes NullableInt32 `json:"noDataMinutes"`
	// How far behind live the evaluated window is held, on top of the reader's settle grace. `null` means no extra delay.
	DelayMinutes NullableInt32 `json:"delayMinutes"`
	// Close a live instance that has gone this long without a fresh verdict. `null` never auto-resolves.
	AutoResolveMinutes NullableInt32 `json:"autoResolveMinutes"`
	// For a `composite` rule, the child rules and how their states combine. `null` on every other kind.
	Composite NullableAlertCompositeSpec `json:"composite"`
	// Lookback window (hours) the metric is aggregated over.
	WindowHours int32 `json:"windowHours"`
	// Width of the buckets the window is split into, in minutes. `null` divides the window into 12 equal buckets.
	BucketMinutes NullableInt32 `json:"bucketMinutes"`
	// How many buckets must breach before the rule fires. `null` means every bucket that had data.
	RequiredBuckets NullableInt32 `json:"requiredBuckets"`
	// Severity of the raised alert.
	Severity string `json:"severity"`
	// Whether the rule is evaluated by the cron.
	Enabled bool `json:"enabled"`
	Notify NullableNotificationTarget `json:"notify"`
	// ISO-8601 timestamp of creation.
	CreatedAt string `json:"createdAt"`
	// ISO-8601 timestamp of the last update.
	UpdatedAt string `json:"updatedAt"`
}

type _ListAlertRulesResponseInner ListAlertRulesResponseInner

// NewListAlertRulesResponseInner instantiates a new ListAlertRulesResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAlertRulesResponseInner(id string, name string, metricId string, metricName NullableString, kind string, comparator string, threshold float32, rangeMin NullableFloat32, rangeMax NullableFloat32, sigma NullableFloat32, direction NullableString, sustained bool, warnThreshold NullableFloat32, recoveryThreshold NullableFloat32, groupAlerts bool, maxGroups NullableInt32, noDataMinutes NullableInt32, delayMinutes NullableInt32, autoResolveMinutes NullableInt32, composite NullableAlertCompositeSpec, windowHours int32, bucketMinutes NullableInt32, requiredBuckets NullableInt32, severity string, enabled bool, notify NullableNotificationTarget, createdAt string, updatedAt string) *ListAlertRulesResponseInner {
	this := ListAlertRulesResponseInner{}
	this.Id = id
	this.Name = name
	this.MetricId = metricId
	this.MetricName = metricName
	this.Kind = kind
	this.Comparator = comparator
	this.Threshold = threshold
	this.RangeMin = rangeMin
	this.RangeMax = rangeMax
	this.Sigma = sigma
	this.Direction = direction
	this.Sustained = sustained
	this.WarnThreshold = warnThreshold
	this.RecoveryThreshold = recoveryThreshold
	this.GroupAlerts = groupAlerts
	this.MaxGroups = maxGroups
	this.NoDataMinutes = noDataMinutes
	this.DelayMinutes = delayMinutes
	this.AutoResolveMinutes = autoResolveMinutes
	this.Composite = composite
	this.WindowHours = windowHours
	this.BucketMinutes = bucketMinutes
	this.RequiredBuckets = requiredBuckets
	this.Severity = severity
	this.Enabled = enabled
	this.Notify = notify
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewListAlertRulesResponseInnerWithDefaults instantiates a new ListAlertRulesResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAlertRulesResponseInnerWithDefaults() *ListAlertRulesResponseInner {
	this := ListAlertRulesResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListAlertRulesResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListAlertRulesResponseInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListAlertRulesResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListAlertRulesResponseInner) SetName(v string) {
	o.Name = v
}

// GetMetricId returns the MetricId field value
func (o *ListAlertRulesResponseInner) GetMetricId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetricId
}

// GetMetricIdOk returns a tuple with the MetricId field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetMetricIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetricId, true
}

// SetMetricId sets field value
func (o *ListAlertRulesResponseInner) SetMetricId(v string) {
	o.MetricId = v
}

// GetMetricName returns the MetricName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListAlertRulesResponseInner) GetMetricName() string {
	if o == nil || o.MetricName.Get() == nil {
		var ret string
		return ret
	}

	return *o.MetricName.Get()
}

// GetMetricNameOk returns a tuple with the MetricName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetMetricNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetricName.Get(), o.MetricName.IsSet()
}

// SetMetricName sets field value
func (o *ListAlertRulesResponseInner) SetMetricName(v string) {
	o.MetricName.Set(&v)
}

// GetKind returns the Kind field value
func (o *ListAlertRulesResponseInner) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ListAlertRulesResponseInner) SetKind(v string) {
	o.Kind = v
}

// GetComparator returns the Comparator field value
func (o *ListAlertRulesResponseInner) GetComparator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comparator
}

// GetComparatorOk returns a tuple with the Comparator field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetComparatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comparator, true
}

// SetComparator sets field value
func (o *ListAlertRulesResponseInner) SetComparator(v string) {
	o.Comparator = v
}

// GetThreshold returns the Threshold field value
func (o *ListAlertRulesResponseInner) GetThreshold() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *ListAlertRulesResponseInner) SetThreshold(v float32) {
	o.Threshold = v
}

// GetRangeMin returns the RangeMin field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListAlertRulesResponseInner) GetRangeMin() float32 {
	if o == nil || o.RangeMin.Get() == nil {
		var ret float32
		return ret
	}

	return *o.RangeMin.Get()
}

// GetRangeMinOk returns a tuple with the RangeMin field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetRangeMinOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RangeMin.Get(), o.RangeMin.IsSet()
}

// SetRangeMin sets field value
func (o *ListAlertRulesResponseInner) SetRangeMin(v float32) {
	o.RangeMin.Set(&v)
}

// GetRangeMax returns the RangeMax field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListAlertRulesResponseInner) GetRangeMax() float32 {
	if o == nil || o.RangeMax.Get() == nil {
		var ret float32
		return ret
	}

	return *o.RangeMax.Get()
}

// GetRangeMaxOk returns a tuple with the RangeMax field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetRangeMaxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RangeMax.Get(), o.RangeMax.IsSet()
}

// SetRangeMax sets field value
func (o *ListAlertRulesResponseInner) SetRangeMax(v float32) {
	o.RangeMax.Set(&v)
}

// GetSigma returns the Sigma field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListAlertRulesResponseInner) GetSigma() float32 {
	if o == nil || o.Sigma.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Sigma.Get()
}

// GetSigmaOk returns a tuple with the Sigma field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetSigmaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sigma.Get(), o.Sigma.IsSet()
}

// SetSigma sets field value
func (o *ListAlertRulesResponseInner) SetSigma(v float32) {
	o.Sigma.Set(&v)
}

// GetDirection returns the Direction field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListAlertRulesResponseInner) GetDirection() string {
	if o == nil || o.Direction.Get() == nil {
		var ret string
		return ret
	}

	return *o.Direction.Get()
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Direction.Get(), o.Direction.IsSet()
}

// SetDirection sets field value
func (o *ListAlertRulesResponseInner) SetDirection(v string) {
	o.Direction.Set(&v)
}

// GetSustained returns the Sustained field value
func (o *ListAlertRulesResponseInner) GetSustained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sustained
}

// GetSustainedOk returns a tuple with the Sustained field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetSustainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sustained, true
}

// SetSustained sets field value
func (o *ListAlertRulesResponseInner) SetSustained(v bool) {
	o.Sustained = v
}

// GetWarnThreshold returns the WarnThreshold field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListAlertRulesResponseInner) GetWarnThreshold() float32 {
	if o == nil || o.WarnThreshold.Get() == nil {
		var ret float32
		return ret
	}

	return *o.WarnThreshold.Get()
}

// GetWarnThresholdOk returns a tuple with the WarnThreshold field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetWarnThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarnThreshold.Get(), o.WarnThreshold.IsSet()
}

// SetWarnThreshold sets field value
func (o *ListAlertRulesResponseInner) SetWarnThreshold(v float32) {
	o.WarnThreshold.Set(&v)
}

// GetRecoveryThreshold returns the RecoveryThreshold field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListAlertRulesResponseInner) GetRecoveryThreshold() float32 {
	if o == nil || o.RecoveryThreshold.Get() == nil {
		var ret float32
		return ret
	}

	return *o.RecoveryThreshold.Get()
}

// GetRecoveryThresholdOk returns a tuple with the RecoveryThreshold field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetRecoveryThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecoveryThreshold.Get(), o.RecoveryThreshold.IsSet()
}

// SetRecoveryThreshold sets field value
func (o *ListAlertRulesResponseInner) SetRecoveryThreshold(v float32) {
	o.RecoveryThreshold.Set(&v)
}

// GetGroupAlerts returns the GroupAlerts field value
func (o *ListAlertRulesResponseInner) GetGroupAlerts() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.GroupAlerts
}

// GetGroupAlertsOk returns a tuple with the GroupAlerts field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetGroupAlertsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupAlerts, true
}

// SetGroupAlerts sets field value
func (o *ListAlertRulesResponseInner) SetGroupAlerts(v bool) {
	o.GroupAlerts = v
}

// GetMaxGroups returns the MaxGroups field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetMaxGroups() int32 {
	if o == nil || o.MaxGroups.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MaxGroups.Get()
}

// GetMaxGroupsOk returns a tuple with the MaxGroups field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetMaxGroupsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxGroups.Get(), o.MaxGroups.IsSet()
}

// SetMaxGroups sets field value
func (o *ListAlertRulesResponseInner) SetMaxGroups(v int32) {
	o.MaxGroups.Set(&v)
}

// GetNoDataMinutes returns the NoDataMinutes field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetNoDataMinutes() int32 {
	if o == nil || o.NoDataMinutes.Get() == nil {
		var ret int32
		return ret
	}

	return *o.NoDataMinutes.Get()
}

// GetNoDataMinutesOk returns a tuple with the NoDataMinutes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetNoDataMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NoDataMinutes.Get(), o.NoDataMinutes.IsSet()
}

// SetNoDataMinutes sets field value
func (o *ListAlertRulesResponseInner) SetNoDataMinutes(v int32) {
	o.NoDataMinutes.Set(&v)
}

// GetDelayMinutes returns the DelayMinutes field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetDelayMinutes() int32 {
	if o == nil || o.DelayMinutes.Get() == nil {
		var ret int32
		return ret
	}

	return *o.DelayMinutes.Get()
}

// GetDelayMinutesOk returns a tuple with the DelayMinutes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetDelayMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DelayMinutes.Get(), o.DelayMinutes.IsSet()
}

// SetDelayMinutes sets field value
func (o *ListAlertRulesResponseInner) SetDelayMinutes(v int32) {
	o.DelayMinutes.Set(&v)
}

// GetAutoResolveMinutes returns the AutoResolveMinutes field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetAutoResolveMinutes() int32 {
	if o == nil || o.AutoResolveMinutes.Get() == nil {
		var ret int32
		return ret
	}

	return *o.AutoResolveMinutes.Get()
}

// GetAutoResolveMinutesOk returns a tuple with the AutoResolveMinutes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetAutoResolveMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoResolveMinutes.Get(), o.AutoResolveMinutes.IsSet()
}

// SetAutoResolveMinutes sets field value
func (o *ListAlertRulesResponseInner) SetAutoResolveMinutes(v int32) {
	o.AutoResolveMinutes.Set(&v)
}

// GetComposite returns the Composite field value
// If the value is explicit nil, the zero value for AlertCompositeSpec will be returned
func (o *ListAlertRulesResponseInner) GetComposite() AlertCompositeSpec {
	if o == nil || o.Composite.Get() == nil {
		var ret AlertCompositeSpec
		return ret
	}

	return *o.Composite.Get()
}

// GetCompositeOk returns a tuple with the Composite field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetCompositeOk() (*AlertCompositeSpec, bool) {
	if o == nil {
		return nil, false
	}
	return o.Composite.Get(), o.Composite.IsSet()
}

// SetComposite sets field value
func (o *ListAlertRulesResponseInner) SetComposite(v AlertCompositeSpec) {
	o.Composite.Set(&v)
}

// GetWindowHours returns the WindowHours field value
func (o *ListAlertRulesResponseInner) GetWindowHours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindowHours
}

// GetWindowHoursOk returns a tuple with the WindowHours field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetWindowHoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowHours, true
}

// SetWindowHours sets field value
func (o *ListAlertRulesResponseInner) SetWindowHours(v int32) {
	o.WindowHours = v
}

// GetBucketMinutes returns the BucketMinutes field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetBucketMinutes() int32 {
	if o == nil || o.BucketMinutes.Get() == nil {
		var ret int32
		return ret
	}

	return *o.BucketMinutes.Get()
}

// GetBucketMinutesOk returns a tuple with the BucketMinutes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetBucketMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BucketMinutes.Get(), o.BucketMinutes.IsSet()
}

// SetBucketMinutes sets field value
func (o *ListAlertRulesResponseInner) SetBucketMinutes(v int32) {
	o.BucketMinutes.Set(&v)
}

// GetRequiredBuckets returns the RequiredBuckets field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListAlertRulesResponseInner) GetRequiredBuckets() int32 {
	if o == nil || o.RequiredBuckets.Get() == nil {
		var ret int32
		return ret
	}

	return *o.RequiredBuckets.Get()
}

// GetRequiredBucketsOk returns a tuple with the RequiredBuckets field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetRequiredBucketsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredBuckets.Get(), o.RequiredBuckets.IsSet()
}

// SetRequiredBuckets sets field value
func (o *ListAlertRulesResponseInner) SetRequiredBuckets(v int32) {
	o.RequiredBuckets.Set(&v)
}

// GetSeverity returns the Severity field value
func (o *ListAlertRulesResponseInner) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ListAlertRulesResponseInner) SetSeverity(v string) {
	o.Severity = v
}

// GetEnabled returns the Enabled field value
func (o *ListAlertRulesResponseInner) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ListAlertRulesResponseInner) SetEnabled(v bool) {
	o.Enabled = v
}

// GetNotify returns the Notify field value
// If the value is explicit nil, the zero value for NotificationTarget will be returned
func (o *ListAlertRulesResponseInner) GetNotify() NotificationTarget {
	if o == nil || o.Notify.Get() == nil {
		var ret NotificationTarget
		return ret
	}

	return *o.Notify.Get()
}

// GetNotifyOk returns a tuple with the Notify field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAlertRulesResponseInner) GetNotifyOk() (*NotificationTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notify.Get(), o.Notify.IsSet()
}

// SetNotify sets field value
func (o *ListAlertRulesResponseInner) SetNotify(v NotificationTarget) {
	o.Notify.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListAlertRulesResponseInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListAlertRulesResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListAlertRulesResponseInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListAlertRulesResponseInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListAlertRulesResponseInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o ListAlertRulesResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAlertRulesResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["metricId"] = o.MetricId
	toSerialize["metricName"] = o.MetricName.Get()
	toSerialize["kind"] = o.Kind
	toSerialize["comparator"] = o.Comparator
	toSerialize["threshold"] = o.Threshold
	toSerialize["rangeMin"] = o.RangeMin.Get()
	toSerialize["rangeMax"] = o.RangeMax.Get()
	toSerialize["sigma"] = o.Sigma.Get()
	toSerialize["direction"] = o.Direction.Get()
	toSerialize["sustained"] = o.Sustained
	toSerialize["warnThreshold"] = o.WarnThreshold.Get()
	toSerialize["recoveryThreshold"] = o.RecoveryThreshold.Get()
	toSerialize["groupAlerts"] = o.GroupAlerts
	toSerialize["maxGroups"] = o.MaxGroups.Get()
	toSerialize["noDataMinutes"] = o.NoDataMinutes.Get()
	toSerialize["delayMinutes"] = o.DelayMinutes.Get()
	toSerialize["autoResolveMinutes"] = o.AutoResolveMinutes.Get()
	toSerialize["composite"] = o.Composite.Get()
	toSerialize["windowHours"] = o.WindowHours
	toSerialize["bucketMinutes"] = o.BucketMinutes.Get()
	toSerialize["requiredBuckets"] = o.RequiredBuckets.Get()
	toSerialize["severity"] = o.Severity
	toSerialize["enabled"] = o.Enabled
	toSerialize["notify"] = o.Notify.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ListAlertRulesResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"metricId",
		"metricName",
		"kind",
		"comparator",
		"threshold",
		"rangeMin",
		"rangeMax",
		"sigma",
		"direction",
		"sustained",
		"warnThreshold",
		"recoveryThreshold",
		"groupAlerts",
		"maxGroups",
		"noDataMinutes",
		"delayMinutes",
		"autoResolveMinutes",
		"composite",
		"windowHours",
		"bucketMinutes",
		"requiredBuckets",
		"severity",
		"enabled",
		"notify",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAlertRulesResponseInner := _ListAlertRulesResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAlertRulesResponseInner)

	if err != nil {
		return err
	}

	*o = ListAlertRulesResponseInner(varListAlertRulesResponseInner)

	return err
}

type NullableListAlertRulesResponseInner struct {
	value *ListAlertRulesResponseInner
	isSet bool
}

func (v NullableListAlertRulesResponseInner) Get() *ListAlertRulesResponseInner {
	return v.value
}

func (v *NullableListAlertRulesResponseInner) Set(val *ListAlertRulesResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlertRulesResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlertRulesResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlertRulesResponseInner(val *ListAlertRulesResponseInner) *NullableListAlertRulesResponseInner {
	return &NullableListAlertRulesResponseInner{value: val, isSet: true}
}

func (v NullableListAlertRulesResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlertRulesResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


