/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGateTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGateTemplateResponse{}

// UpdateGateTemplateResponse struct for UpdateGateTemplateResponse
type UpdateGateTemplateResponse struct {
	Id string `json:"id"`
}

type _UpdateGateTemplateResponse UpdateGateTemplateResponse

// NewUpdateGateTemplateResponse instantiates a new UpdateGateTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGateTemplateResponse(id string) *UpdateGateTemplateResponse {
	this := UpdateGateTemplateResponse{}
	this.Id = id
	return &this
}

// NewUpdateGateTemplateResponseWithDefaults instantiates a new UpdateGateTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGateTemplateResponseWithDefaults() *UpdateGateTemplateResponse {
	this := UpdateGateTemplateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateGateTemplateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateGateTemplateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateGateTemplateResponse) SetId(v string) {
	o.Id = v
}

func (o UpdateGateTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGateTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *UpdateGateTemplateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGateTemplateResponse := _UpdateGateTemplateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGateTemplateResponse)

	if err != nil {
		return err
	}

	*o = UpdateGateTemplateResponse(varUpdateGateTemplateResponse)

	return err
}

type NullableUpdateGateTemplateResponse struct {
	value *UpdateGateTemplateResponse
	isSet bool
}

func (v NullableUpdateGateTemplateResponse) Get() *UpdateGateTemplateResponse {
	return v.value
}

func (v *NullableUpdateGateTemplateResponse) Set(val *UpdateGateTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGateTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGateTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGateTemplateResponse(val *UpdateGateTemplateResponse) *NullableUpdateGateTemplateResponse {
	return &NullableUpdateGateTemplateResponse{value: val, isSet: true}
}

func (v NullableUpdateGateTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGateTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


