/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOpsItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOpsItemResponse{}

// CreateOpsItemResponse Response for the create endpoints.
type CreateOpsItemResponse struct {
	// Newly created item id.
	Id string `json:"id"`
	// Per-project item number assigned to the new item.
	Number NullableFloat32 `json:"number,omitempty"`
}

type _CreateOpsItemResponse CreateOpsItemResponse

// NewCreateOpsItemResponse instantiates a new CreateOpsItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOpsItemResponse(id string) *CreateOpsItemResponse {
	this := CreateOpsItemResponse{}
	this.Id = id
	return &this
}

// NewCreateOpsItemResponseWithDefaults instantiates a new CreateOpsItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOpsItemResponseWithDefaults() *CreateOpsItemResponse {
	this := CreateOpsItemResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateOpsItemResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateOpsItemResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateOpsItemResponse) SetId(v string) {
	o.Id = v
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOpsItemResponse) GetNumber() float32 {
	if o == nil || IsNil(o.Number.Get()) {
		var ret float32
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOpsItemResponse) GetNumberOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *CreateOpsItemResponse) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableFloat32 and assigns it to the Number field.
func (o *CreateOpsItemResponse) SetNumber(v float32) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *CreateOpsItemResponse) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *CreateOpsItemResponse) UnsetNumber() {
	o.Number.Unset()
}

func (o CreateOpsItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOpsItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	return toSerialize, nil
}

func (o *CreateOpsItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOpsItemResponse := _CreateOpsItemResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOpsItemResponse)

	if err != nil {
		return err
	}

	*o = CreateOpsItemResponse(varCreateOpsItemResponse)

	return err
}

type NullableCreateOpsItemResponse struct {
	value *CreateOpsItemResponse
	isSet bool
}

func (v NullableCreateOpsItemResponse) Get() *CreateOpsItemResponse {
	return v.value
}

func (v *NullableCreateOpsItemResponse) Set(val *CreateOpsItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOpsItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOpsItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOpsItemResponse(val *CreateOpsItemResponse) *NullableCreateOpsItemResponse {
	return &NullableCreateOpsItemResponse{value: val, isSet: true}
}

func (v NullableCreateOpsItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOpsItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


