/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateI18nKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateI18nKeyRequest{}

// UpdateI18nKeyRequest Body for `PUT /api/admin/i18n/keys/{id}`. Updates one existing key's value.
type UpdateI18nKeyRequest struct {
	// New value for the key (the only overwrite path).
	Value string `json:"value"`
	// Optional human note to store with the key.
	Description *string `json:"description,omitempty"`
}

type _UpdateI18nKeyRequest UpdateI18nKeyRequest

// NewUpdateI18nKeyRequest instantiates a new UpdateI18nKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateI18nKeyRequest(value string) *UpdateI18nKeyRequest {
	this := UpdateI18nKeyRequest{}
	this.Value = value
	return &this
}

// NewUpdateI18nKeyRequestWithDefaults instantiates a new UpdateI18nKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateI18nKeyRequestWithDefaults() *UpdateI18nKeyRequest {
	this := UpdateI18nKeyRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *UpdateI18nKeyRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateI18nKeyRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *UpdateI18nKeyRequest) SetValue(v string) {
	o.Value = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateI18nKeyRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateI18nKeyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateI18nKeyRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateI18nKeyRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateI18nKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateI18nKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *UpdateI18nKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateI18nKeyRequest := _UpdateI18nKeyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateI18nKeyRequest)

	if err != nil {
		return err
	}

	*o = UpdateI18nKeyRequest(varUpdateI18nKeyRequest)

	return err
}

type NullableUpdateI18nKeyRequest struct {
	value *UpdateI18nKeyRequest
	isSet bool
}

func (v NullableUpdateI18nKeyRequest) Get() *UpdateI18nKeyRequest {
	return v.value
}

func (v *NullableUpdateI18nKeyRequest) Set(val *UpdateI18nKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateI18nKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateI18nKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateI18nKeyRequest(val *UpdateI18nKeyRequest) *NullableUpdateI18nKeyRequest {
	return &NullableUpdateI18nKeyRequest{value: val, isSet: true}
}

func (v NullableUpdateI18nKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateI18nKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


