/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOAuthConnectorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOAuthConnectorRequest{}

// CreateOAuthConnectorRequest Create an OAuth/app connector stub. The connector is created `enabled: false` with empty `config` and no credentials; the provider's OAuth flow then attaches credentials and enables it.
type CreateOAuthConnectorRequest struct {
	// OAuth/app connector destination.
	Provider string `json:"provider"`
	// Human-readable connector label.
	Name string `json:"name"`
	// Events to subscribe to. At least one is required.
	Events []ConnectorEvent `json:"events"`
}

type _CreateOAuthConnectorRequest CreateOAuthConnectorRequest

// NewCreateOAuthConnectorRequest instantiates a new CreateOAuthConnectorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOAuthConnectorRequest(provider string, name string, events []ConnectorEvent) *CreateOAuthConnectorRequest {
	this := CreateOAuthConnectorRequest{}
	this.Provider = provider
	this.Name = name
	this.Events = events
	return &this
}

// NewCreateOAuthConnectorRequestWithDefaults instantiates a new CreateOAuthConnectorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOAuthConnectorRequestWithDefaults() *CreateOAuthConnectorRequest {
	this := CreateOAuthConnectorRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *CreateOAuthConnectorRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateOAuthConnectorRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateOAuthConnectorRequest) SetProvider(v string) {
	o.Provider = v
}

// GetName returns the Name field value
func (o *CreateOAuthConnectorRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOAuthConnectorRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOAuthConnectorRequest) SetName(v string) {
	o.Name = v
}

// GetEvents returns the Events field value
func (o *CreateOAuthConnectorRequest) GetEvents() []ConnectorEvent {
	if o == nil {
		var ret []ConnectorEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *CreateOAuthConnectorRequest) GetEventsOk() ([]ConnectorEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *CreateOAuthConnectorRequest) SetEvents(v []ConnectorEvent) {
	o.Events = v
}

func (o CreateOAuthConnectorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOAuthConnectorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["name"] = o.Name
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *CreateOAuthConnectorRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"name",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOAuthConnectorRequest := _CreateOAuthConnectorRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOAuthConnectorRequest)

	if err != nil {
		return err
	}

	*o = CreateOAuthConnectorRequest(varCreateOAuthConnectorRequest)

	return err
}

type NullableCreateOAuthConnectorRequest struct {
	value *CreateOAuthConnectorRequest
	isSet bool
}

func (v NullableCreateOAuthConnectorRequest) Get() *CreateOAuthConnectorRequest {
	return v.value
}

func (v *NullableCreateOAuthConnectorRequest) Set(val *CreateOAuthConnectorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOAuthConnectorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOAuthConnectorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOAuthConnectorRequest(val *CreateOAuthConnectorRequest) *NullableCreateOAuthConnectorRequest {
	return &NullableCreateOAuthConnectorRequest{value: val, isSet: true}
}

func (v NullableCreateOAuthConnectorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOAuthConnectorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


