/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the GetOpsItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOpsItemResponse{}

// GetOpsItemResponse One queue item — any type.
type GetOpsItemResponse struct {
	// Stable opaque item id.
	Id string `json:"id"`
	// Per-project item number (the `#7` handle), or `null` if unnumbered.
	Number NullableFloat32 `json:"number"`
	// Queue item type. `bug` and `feature_request` are user-fileable; `error` and `alert` tickets are auto-filed by the platform.
	Type string `json:"type"`
	// One-line item title.
	Title string `json:"title"`
	// Lifecycle status of a queue item.
	Status string `json:"status"`
	// Triage priority of a queue item.
	Priority NullableString `json:"priority"`
	// Source reference for auto-filed tickets (e.g. an error fingerprint).
	SourceRef NullableString `json:"sourceRef,omitempty"`
	// ISO-8601 creation timestamp.
	CreatedAt string `json:"createdAt"`
	AdditionalProperties map[string]interface{}
}

type _GetOpsItemResponse GetOpsItemResponse

// NewGetOpsItemResponse instantiates a new GetOpsItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOpsItemResponse(id string, number NullableFloat32, type_ string, title string, status string, priority NullableString, createdAt string) *GetOpsItemResponse {
	this := GetOpsItemResponse{}
	this.Id = id
	this.Number = number
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Priority = priority
	this.CreatedAt = createdAt
	return &this
}

// NewGetOpsItemResponseWithDefaults instantiates a new GetOpsItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOpsItemResponseWithDefaults() *GetOpsItemResponse {
	this := GetOpsItemResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetOpsItemResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetOpsItemResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetOpsItemResponse) SetId(v string) {
	o.Id = v
}

// GetNumber returns the Number field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *GetOpsItemResponse) GetNumber() float32 {
	if o == nil || o.Number.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOpsItemResponse) GetNumberOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// SetNumber sets field value
func (o *GetOpsItemResponse) SetNumber(v float32) {
	o.Number.Set(&v)
}

// GetType returns the Type field value
func (o *GetOpsItemResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetOpsItemResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetOpsItemResponse) SetType(v string) {
	o.Type = v
}

// GetTitle returns the Title field value
func (o *GetOpsItemResponse) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GetOpsItemResponse) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GetOpsItemResponse) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *GetOpsItemResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetOpsItemResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetOpsItemResponse) SetStatus(v string) {
	o.Status = v
}

// GetPriority returns the Priority field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOpsItemResponse) GetPriority() string {
	if o == nil || o.Priority.Get() == nil {
		var ret string
		return ret
	}

	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOpsItemResponse) GetPriorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// SetPriority sets field value
func (o *GetOpsItemResponse) SetPriority(v string) {
	o.Priority.Set(&v)
}

// GetSourceRef returns the SourceRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetOpsItemResponse) GetSourceRef() string {
	if o == nil || IsNil(o.SourceRef.Get()) {
		var ret string
		return ret
	}
	return *o.SourceRef.Get()
}

// GetSourceRefOk returns a tuple with the SourceRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOpsItemResponse) GetSourceRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceRef.Get(), o.SourceRef.IsSet()
}

// HasSourceRef returns a boolean if a field has been set.
func (o *GetOpsItemResponse) HasSourceRef() bool {
	if o != nil && o.SourceRef.IsSet() {
		return true
	}

	return false
}

// SetSourceRef gets a reference to the given NullableString and assigns it to the SourceRef field.
func (o *GetOpsItemResponse) SetSourceRef(v string) {
	o.SourceRef.Set(&v)
}
// SetSourceRefNil sets the value for SourceRef to be an explicit nil
func (o *GetOpsItemResponse) SetSourceRefNil() {
	o.SourceRef.Set(nil)
}

// UnsetSourceRef ensures that no value is present for SourceRef, not even an explicit nil
func (o *GetOpsItemResponse) UnsetSourceRef() {
	o.SourceRef.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetOpsItemResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetOpsItemResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetOpsItemResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o GetOpsItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOpsItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["number"] = o.Number.Get()
	toSerialize["type"] = o.Type
	toSerialize["title"] = o.Title
	toSerialize["status"] = o.Status
	toSerialize["priority"] = o.Priority.Get()
	if o.SourceRef.IsSet() {
		toSerialize["sourceRef"] = o.SourceRef.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOpsItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"number",
		"type",
		"title",
		"status",
		"priority",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOpsItemResponse := _GetOpsItemResponse{}

	err = json.Unmarshal(data, &varGetOpsItemResponse)

	if err != nil {
		return err
	}

	*o = GetOpsItemResponse(varGetOpsItemResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "number")
		delete(additionalProperties, "type")
		delete(additionalProperties, "title")
		delete(additionalProperties, "status")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "sourceRef")
		delete(additionalProperties, "createdAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOpsItemResponse struct {
	value *GetOpsItemResponse
	isSet bool
}

func (v NullableGetOpsItemResponse) Get() *GetOpsItemResponse {
	return v.value
}

func (v *NullableGetOpsItemResponse) Set(val *GetOpsItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOpsItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOpsItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOpsItemResponse(val *GetOpsItemResponse) *NullableGetOpsItemResponse {
	return &NullableGetOpsItemResponse{value: val, isSet: true}
}

func (v NullableGetOpsItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOpsItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


