/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpsAgentProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpsAgentProfile{}

// OpsAgentProfile One connected, assignable AI agent (an authenticated trigger connector).
type OpsAgentProfile struct {
	// The connector row id — what an agent assignment stores.
	ConnectorId string `json:"connectorId"`
	// The trigger-connector provider backing this agent.
	Provider string `json:"provider"`
	// Display name — the connector's `name`, or the provider default (e.g. \"Claude\").
	Name string `json:"name"`
	// Mention/search handle — the kebab-cased name (e.g. `claude`).
	Handle string `json:"handle"`
}

type _OpsAgentProfile OpsAgentProfile

// NewOpsAgentProfile instantiates a new OpsAgentProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsAgentProfile(connectorId string, provider string, name string, handle string) *OpsAgentProfile {
	this := OpsAgentProfile{}
	this.ConnectorId = connectorId
	this.Provider = provider
	this.Name = name
	this.Handle = handle
	return &this
}

// NewOpsAgentProfileWithDefaults instantiates a new OpsAgentProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsAgentProfileWithDefaults() *OpsAgentProfile {
	this := OpsAgentProfile{}
	return &this
}

// GetConnectorId returns the ConnectorId field value
func (o *OpsAgentProfile) GetConnectorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectorId
}

// GetConnectorIdOk returns a tuple with the ConnectorId field value
// and a boolean to check if the value has been set.
func (o *OpsAgentProfile) GetConnectorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorId, true
}

// SetConnectorId sets field value
func (o *OpsAgentProfile) SetConnectorId(v string) {
	o.ConnectorId = v
}

// GetProvider returns the Provider field value
func (o *OpsAgentProfile) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *OpsAgentProfile) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *OpsAgentProfile) SetProvider(v string) {
	o.Provider = v
}

// GetName returns the Name field value
func (o *OpsAgentProfile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpsAgentProfile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpsAgentProfile) SetName(v string) {
	o.Name = v
}

// GetHandle returns the Handle field value
func (o *OpsAgentProfile) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *OpsAgentProfile) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *OpsAgentProfile) SetHandle(v string) {
	o.Handle = v
}

func (o OpsAgentProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpsAgentProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectorId"] = o.ConnectorId
	toSerialize["provider"] = o.Provider
	toSerialize["name"] = o.Name
	toSerialize["handle"] = o.Handle
	return toSerialize, nil
}

func (o *OpsAgentProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectorId",
		"provider",
		"name",
		"handle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpsAgentProfile := _OpsAgentProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpsAgentProfile)

	if err != nil {
		return err
	}

	*o = OpsAgentProfile(varOpsAgentProfile)

	return err
}

type NullableOpsAgentProfile struct {
	value *OpsAgentProfile
	isSet bool
}

func (v NullableOpsAgentProfile) Get() *OpsAgentProfile {
	return v.value
}

func (v *NullableOpsAgentProfile) Set(val *OpsAgentProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsAgentProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsAgentProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsAgentProfile(val *OpsAgentProfile) *NullableOpsAgentProfile {
	return &NullableOpsAgentProfile{value: val, isSet: true}
}

func (v NullableOpsAgentProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsAgentProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


