/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMetricsResponseInnerQueryIr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetricsResponseInnerQueryIr{}

// ListMetricsResponseInnerQueryIr Typed query IR stored for the metric.
type ListMetricsResponseInnerQueryIr struct {
	Agg ListMetricsResponseInnerQueryIrAgg `json:"agg"`
	// Source event name (must equal `event_name`).
	Metric string `json:"metric"`
	// Numeric property summed/averaged for `sum`/`avg`/quantile aggregations.
	ValueLabel *string `json:"valueLabel,omitempty"`
	// Label filters on the event.
	Filters []ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner `json:"filters"`
	GroupBy *ListMetricsResponseInnerQueryIrGroupBy `json:"groupBy,omitempty"`
}

type _ListMetricsResponseInnerQueryIr ListMetricsResponseInnerQueryIr

// NewListMetricsResponseInnerQueryIr instantiates a new ListMetricsResponseInnerQueryIr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetricsResponseInnerQueryIr(agg ListMetricsResponseInnerQueryIrAgg, metric string, filters []ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner) *ListMetricsResponseInnerQueryIr {
	this := ListMetricsResponseInnerQueryIr{}
	this.Agg = agg
	this.Metric = metric
	this.Filters = filters
	return &this
}

// NewListMetricsResponseInnerQueryIrWithDefaults instantiates a new ListMetricsResponseInnerQueryIr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetricsResponseInnerQueryIrWithDefaults() *ListMetricsResponseInnerQueryIr {
	this := ListMetricsResponseInnerQueryIr{}
	return &this
}

// GetAgg returns the Agg field value
func (o *ListMetricsResponseInnerQueryIr) GetAgg() ListMetricsResponseInnerQueryIrAgg {
	if o == nil {
		var ret ListMetricsResponseInnerQueryIrAgg
		return ret
	}

	return o.Agg
}

// GetAggOk returns a tuple with the Agg field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIr) GetAggOk() (*ListMetricsResponseInnerQueryIrAgg, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Agg, true
}

// SetAgg sets field value
func (o *ListMetricsResponseInnerQueryIr) SetAgg(v ListMetricsResponseInnerQueryIrAgg) {
	o.Agg = v
}

// GetMetric returns the Metric field value
func (o *ListMetricsResponseInnerQueryIr) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIr) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *ListMetricsResponseInnerQueryIr) SetMetric(v string) {
	o.Metric = v
}

// GetValueLabel returns the ValueLabel field value if set, zero value otherwise.
func (o *ListMetricsResponseInnerQueryIr) GetValueLabel() string {
	if o == nil || IsNil(o.ValueLabel) {
		var ret string
		return ret
	}
	return *o.ValueLabel
}

// GetValueLabelOk returns a tuple with the ValueLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIr) GetValueLabelOk() (*string, bool) {
	if o == nil || IsNil(o.ValueLabel) {
		return nil, false
	}
	return o.ValueLabel, true
}

// HasValueLabel returns a boolean if a field has been set.
func (o *ListMetricsResponseInnerQueryIr) HasValueLabel() bool {
	if o != nil && !IsNil(o.ValueLabel) {
		return true
	}

	return false
}

// SetValueLabel gets a reference to the given string and assigns it to the ValueLabel field.
func (o *ListMetricsResponseInnerQueryIr) SetValueLabel(v string) {
	o.ValueLabel = &v
}

// GetFilters returns the Filters field value
func (o *ListMetricsResponseInnerQueryIr) GetFilters() []ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner {
	if o == nil {
		var ret []ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner
		return ret
	}

	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIr) GetFiltersOk() ([]ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filters, true
}

// SetFilters sets field value
func (o *ListMetricsResponseInnerQueryIr) SetFilters(v []ListMetricsResponseInnerQueryIrAggOneOf9NumeratorFiltersInner) {
	o.Filters = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *ListMetricsResponseInnerQueryIr) GetGroupBy() ListMetricsResponseInnerQueryIrGroupBy {
	if o == nil || IsNil(o.GroupBy) {
		var ret ListMetricsResponseInnerQueryIrGroupBy
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIr) GetGroupByOk() (*ListMetricsResponseInnerQueryIrGroupBy, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *ListMetricsResponseInnerQueryIr) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given ListMetricsResponseInnerQueryIrGroupBy and assigns it to the GroupBy field.
func (o *ListMetricsResponseInnerQueryIr) SetGroupBy(v ListMetricsResponseInnerQueryIrGroupBy) {
	o.GroupBy = &v
}

func (o ListMetricsResponseInnerQueryIr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetricsResponseInnerQueryIr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agg"] = o.Agg
	toSerialize["metric"] = o.Metric
	if !IsNil(o.ValueLabel) {
		toSerialize["valueLabel"] = o.ValueLabel
	}
	toSerialize["filters"] = o.Filters
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	return toSerialize, nil
}

func (o *ListMetricsResponseInnerQueryIr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agg",
		"metric",
		"filters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetricsResponseInnerQueryIr := _ListMetricsResponseInnerQueryIr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMetricsResponseInnerQueryIr)

	if err != nil {
		return err
	}

	*o = ListMetricsResponseInnerQueryIr(varListMetricsResponseInnerQueryIr)

	return err
}

type NullableListMetricsResponseInnerQueryIr struct {
	value *ListMetricsResponseInnerQueryIr
	isSet bool
}

func (v NullableListMetricsResponseInnerQueryIr) Get() *ListMetricsResponseInnerQueryIr {
	return v.value
}

func (v *NullableListMetricsResponseInnerQueryIr) Set(val *ListMetricsResponseInnerQueryIr) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetricsResponseInnerQueryIr) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetricsResponseInnerQueryIr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetricsResponseInnerQueryIr(val *ListMetricsResponseInnerQueryIr) *NullableListMetricsResponseInnerQueryIr {
	return &NullableListMetricsResponseInnerQueryIr{value: val, isSet: true}
}

func (v NullableListMetricsResponseInnerQueryIr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetricsResponseInnerQueryIr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


