/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCurrentProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentProjectResponse{}

// GetCurrentProjectResponse The project the caller's auth header resolves to. The shape is open — additional project fields may be present. Stripe billing internals (`stripeCustomerId`, the `stripeItemId*` family) are intentionally undocumented.
type GetCurrentProjectResponse struct {
	// Stable opaque project id.
	Id string `json:"id"`
	// Project name.
	Name string `json:"name"`
	// Project domain, or `null` if unset.
	Domain NullableString `json:"domain"`
	// Email of the account that owns the project.
	OwnerEmail string `json:"ownerEmail"`
	// Billing plan tier.
	Plan string `json:"plan"`
	// Project lifecycle status.
	Status string `json:"status"`
	// Stripe subscription status (`none`, `active`, `trialing`, `past_due`, …).
	SubscriptionStatus string `json:"subscriptionStatus"`
	// Billing cadence.
	BillingInterval string `json:"billingInterval"`
	// ISO-8601 end of the current billing period, or `null`.
	CurrentPeriodEnd NullableString `json:"currentPeriodEnd"`
	// ISO-8601 trial end, or `null` if not trialing.
	TrialEndsAt NullableString `json:"trialEndsAt"`
	// `1` if the subscription is set to cancel at period end, else `0`.
	CancelAtPeriodEnd float32 `json:"cancelAtPeriodEnd"`
	ModuleTranslations GetCurrentProjectResponseModuleTranslations `json:"moduleTranslations"`
	ModuleConfigs GetCurrentProjectResponseModuleTranslations `json:"moduleConfigs"`
	ModuleGates GetCurrentProjectResponseModuleTranslations `json:"moduleGates"`
	ModuleExperiments GetCurrentProjectResponseModuleTranslations `json:"moduleExperiments"`
	ModuleFeedback GetCurrentProjectResponseModuleTranslations `json:"moduleFeedback"`
	// Verdict power guard — minimum users per arm before a ship/hold verdict.
	MinSampleSize *int32 `json:"minSampleSize,omitempty"`
	// Minimum days an experiment must run before a verdict (peeking guard).
	MinRuntimeDays *int32 `json:"minRuntimeDays,omitempty"`
	// Target statistical power (1−β) feeding the realized-MDE calculation.
	DefaultPower *float32 `json:"defaultPower,omitempty"`
	// Confidence level for the interval surfaced on results.
	CiConfidence *float32 `json:"ciConfidence,omitempty"`
	// Default traffic allocation (basis points) new experiments start with.
	DefaultAllocationPct *int32 `json:"defaultAllocationPct,omitempty"`
	// Default holdout carve-out (basis points) that seeds each new universe's holdout (0 = none).
	DefaultHoldoutBp int32 `json:"defaultHoldoutBp"`
	// Default winsorization percentile new metrics start with.
	DefaultWinsorizePct *int32 `json:"defaultWinsorizePct,omitempty"`
	// Default minimum effect of interest (relative, 0–1) new metrics start with, or null.
	DefaultMei NullableFloat32 `json:"defaultMei,omitempty"`
	// CUPED baseline window — days of pre-experiment history, frozen at start.
	CupedBaselineDays *int32 `json:"cupedBaselineDays,omitempty"`
	// CUPED selection-bias guard — min share of users with a baseline, else skip.
	CupedMinOverlap *float32 `json:"cupedMinOverlap,omitempty"`
	// CUPED — minimum users with a baseline before it runs at all.
	CupedMinBaselineUsers *int32 `json:"cupedMinBaselineUsers,omitempty"`
	// mSPRT prior width — τ = minimum effect of interest × this factor.
	MsprtTauMeiFactor *float32 `json:"msprtTauMeiFactor,omitempty"`
	// mSPRT fallback prior width — τ = this × control SD when no MEI is set.
	MsprtTauSdFactor *float32 `json:"msprtTauSdFactor,omitempty"`
	// SRM chi-square p-value below which the run is called invalid.
	SrmThreshold *float32 `json:"srmThreshold,omitempty"`
	// URL-safe project identifier used in app URLs and SDK config, or `null` if unset.
	Slug NullableString `json:"slug"`
	// Cache-busted URL of the project logo (served from the admin logo route), or `null` when no logo is set.
	Logo NullableString `json:"logo"`
	// Default environment new resources are scoped to.
	DefaultEnv string `json:"defaultEnv"`
	// IANA timezone the project's daily analysis runs in.
	Timezone string `json:"timezone"`
	// Statistical method the experiment analyzer uses.
	StatMethod string `json:"statMethod"`
	// Significance threshold (alpha) for experiment analysis, as a decimal string (e.g. `\"0.05\"`).
	SigThreshold string `json:"sigThreshold"`
	// Whether a failing guardrail auto-rolls back the experiment.
	AutoRollback bool `json:"autoRollback"`
	// Minimum number of days an experiment must run before it can be called.
	MinSampleDays int32 `json:"minSampleDays"`
	ModuleUser GetCurrentProjectResponseModuleTranslations `json:"moduleUser"`
	ModuleEvents GetCurrentProjectResponseModuleTranslations `json:"moduleEvents"`
	AllowPublicTickets GetCurrentProjectResponseModuleTranslations `json:"allowPublicTickets"`
	// Days an `open` tracked error may go unseen before the nightly sweep auto-resolves it. `0` disables auto-close for this project. Ingest reopens a resolved error the moment it recurs, so this never hides a live issue.
	ErrorAutocloseDays int32 `json:"errorAutocloseDays"`
	// Occurrence count a tracked error must cross before an `error` ticket is auto-filed into the ops queue. Customising it requires a paid plan; unentitled projects always run at the platform default of 10.
	ErrorTicketMinOccurrences int32 `json:"errorTicketMinOccurrences"`
	// Stripe subscription id backing the project's billing, or `null` when unsubscribed.
	StripeSubscriptionId NullableString `json:"stripeSubscriptionId"`
	// Pending billing-interval change deferred to period end (only the annual→monthly downgrade), or `null` when no switch is pending.
	ScheduledInterval NullableString `json:"scheduledInterval"`
	SpendLimitEnabled GetCurrentProjectResponseModuleTranslations `json:"spendLimitEnabled"`
	// Advisory monthly spend limit in whole USD, or `null` if unset.
	SpendLimitUsd NullableInt32 `json:"spendLimitUsd"`
	// Email address the spend alert is sent to, or `null` if unset.
	SpendAlertEmail NullableString `json:"spendAlertEmail"`
	// Default person owner (user id) auto-assigned to new `pending_approval` feedback items, or `null` when unset.
	DefaultAssigneePendingApproval NullableString `json:"defaultAssigneePendingApproval"`
	// Default agent owner (connector id) auto-assigned to new `pending_approval` feedback items, or `null` when unset.
	DefaultAssigneeConnectorPendingApproval NullableString `json:"defaultAssigneeConnectorPendingApproval"`
	// Default person owner (user id) auto-assigned to new `open` feedback items, or `null` when unset.
	DefaultAssigneeOpen NullableString `json:"defaultAssigneeOpen"`
	// Default agent owner (connector id) auto-assigned to new `open` feedback items, or `null` when unset.
	DefaultAssigneeConnectorOpen NullableString `json:"defaultAssigneeConnectorOpen"`
	// ISO-8601 timestamp the project was soft-deleted (purged after a 14-day grace period), or `null` when live.
	DeletedAt NullableString `json:"deletedAt"`
	// ISO-8601 timestamp of project creation.
	CreatedAt string `json:"createdAt"`
	// ISO-8601 timestamp of last update.
	UpdatedAt string `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetCurrentProjectResponse GetCurrentProjectResponse

// NewGetCurrentProjectResponse instantiates a new GetCurrentProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentProjectResponse(id string, name string, domain NullableString, ownerEmail string, plan string, status string, subscriptionStatus string, billingInterval string, currentPeriodEnd NullableString, trialEndsAt NullableString, cancelAtPeriodEnd float32, moduleTranslations GetCurrentProjectResponseModuleTranslations, moduleConfigs GetCurrentProjectResponseModuleTranslations, moduleGates GetCurrentProjectResponseModuleTranslations, moduleExperiments GetCurrentProjectResponseModuleTranslations, moduleFeedback GetCurrentProjectResponseModuleTranslations, defaultHoldoutBp int32, slug NullableString, logo NullableString, defaultEnv string, timezone string, statMethod string, sigThreshold string, autoRollback bool, minSampleDays int32, moduleUser GetCurrentProjectResponseModuleTranslations, moduleEvents GetCurrentProjectResponseModuleTranslations, allowPublicTickets GetCurrentProjectResponseModuleTranslations, errorAutocloseDays int32, errorTicketMinOccurrences int32, stripeSubscriptionId NullableString, scheduledInterval NullableString, spendLimitEnabled GetCurrentProjectResponseModuleTranslations, spendLimitUsd NullableInt32, spendAlertEmail NullableString, defaultAssigneePendingApproval NullableString, defaultAssigneeConnectorPendingApproval NullableString, defaultAssigneeOpen NullableString, defaultAssigneeConnectorOpen NullableString, deletedAt NullableString, createdAt string, updatedAt string) *GetCurrentProjectResponse {
	this := GetCurrentProjectResponse{}
	this.Id = id
	this.Name = name
	this.Domain = domain
	this.OwnerEmail = ownerEmail
	this.Plan = plan
	this.Status = status
	this.SubscriptionStatus = subscriptionStatus
	this.BillingInterval = billingInterval
	this.CurrentPeriodEnd = currentPeriodEnd
	this.TrialEndsAt = trialEndsAt
	this.CancelAtPeriodEnd = cancelAtPeriodEnd
	this.ModuleTranslations = moduleTranslations
	this.ModuleConfigs = moduleConfigs
	this.ModuleGates = moduleGates
	this.ModuleExperiments = moduleExperiments
	this.ModuleFeedback = moduleFeedback
	this.DefaultHoldoutBp = defaultHoldoutBp
	this.Slug = slug
	this.Logo = logo
	this.DefaultEnv = defaultEnv
	this.Timezone = timezone
	this.StatMethod = statMethod
	this.SigThreshold = sigThreshold
	this.AutoRollback = autoRollback
	this.MinSampleDays = minSampleDays
	this.ModuleUser = moduleUser
	this.ModuleEvents = moduleEvents
	this.AllowPublicTickets = allowPublicTickets
	this.ErrorAutocloseDays = errorAutocloseDays
	this.ErrorTicketMinOccurrences = errorTicketMinOccurrences
	this.StripeSubscriptionId = stripeSubscriptionId
	this.ScheduledInterval = scheduledInterval
	this.SpendLimitEnabled = spendLimitEnabled
	this.SpendLimitUsd = spendLimitUsd
	this.SpendAlertEmail = spendAlertEmail
	this.DefaultAssigneePendingApproval = defaultAssigneePendingApproval
	this.DefaultAssigneeConnectorPendingApproval = defaultAssigneeConnectorPendingApproval
	this.DefaultAssigneeOpen = defaultAssigneeOpen
	this.DefaultAssigneeConnectorOpen = defaultAssigneeConnectorOpen
	this.DeletedAt = deletedAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetCurrentProjectResponseWithDefaults instantiates a new GetCurrentProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentProjectResponseWithDefaults() *GetCurrentProjectResponse {
	this := GetCurrentProjectResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetCurrentProjectResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCurrentProjectResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetCurrentProjectResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetCurrentProjectResponse) SetName(v string) {
	o.Name = v
}

// GetDomain returns the Domain field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDomain() string {
	if o == nil || o.Domain.Get() == nil {
		var ret string
		return ret
	}

	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// SetDomain sets field value
func (o *GetCurrentProjectResponse) SetDomain(v string) {
	o.Domain.Set(&v)
}

// GetOwnerEmail returns the OwnerEmail field value
func (o *GetCurrentProjectResponse) GetOwnerEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerEmail
}

// GetOwnerEmailOk returns a tuple with the OwnerEmail field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetOwnerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerEmail, true
}

// SetOwnerEmail sets field value
func (o *GetCurrentProjectResponse) SetOwnerEmail(v string) {
	o.OwnerEmail = v
}

// GetPlan returns the Plan field value
func (o *GetCurrentProjectResponse) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *GetCurrentProjectResponse) SetPlan(v string) {
	o.Plan = v
}

// GetStatus returns the Status field value
func (o *GetCurrentProjectResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetCurrentProjectResponse) SetStatus(v string) {
	o.Status = v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value
func (o *GetCurrentProjectResponse) GetSubscriptionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionStatus, true
}

// SetSubscriptionStatus sets field value
func (o *GetCurrentProjectResponse) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = v
}

// GetBillingInterval returns the BillingInterval field value
func (o *GetCurrentProjectResponse) GetBillingInterval() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingInterval
}

// GetBillingIntervalOk returns a tuple with the BillingInterval field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetBillingIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingInterval, true
}

// SetBillingInterval sets field value
func (o *GetCurrentProjectResponse) SetBillingInterval(v string) {
	o.BillingInterval = v
}

// GetCurrentPeriodEnd returns the CurrentPeriodEnd field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetCurrentPeriodEnd() string {
	if o == nil || o.CurrentPeriodEnd.Get() == nil {
		var ret string
		return ret
	}

	return *o.CurrentPeriodEnd.Get()
}

// GetCurrentPeriodEndOk returns a tuple with the CurrentPeriodEnd field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetCurrentPeriodEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentPeriodEnd.Get(), o.CurrentPeriodEnd.IsSet()
}

// SetCurrentPeriodEnd sets field value
func (o *GetCurrentProjectResponse) SetCurrentPeriodEnd(v string) {
	o.CurrentPeriodEnd.Set(&v)
}

// GetTrialEndsAt returns the TrialEndsAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetTrialEndsAt() string {
	if o == nil || o.TrialEndsAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.TrialEndsAt.Get()
}

// GetTrialEndsAtOk returns a tuple with the TrialEndsAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetTrialEndsAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialEndsAt.Get(), o.TrialEndsAt.IsSet()
}

// SetTrialEndsAt sets field value
func (o *GetCurrentProjectResponse) SetTrialEndsAt(v string) {
	o.TrialEndsAt.Set(&v)
}

// GetCancelAtPeriodEnd returns the CancelAtPeriodEnd field value
func (o *GetCurrentProjectResponse) GetCancelAtPeriodEnd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CancelAtPeriodEnd
}

// GetCancelAtPeriodEndOk returns a tuple with the CancelAtPeriodEnd field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCancelAtPeriodEndOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelAtPeriodEnd, true
}

// SetCancelAtPeriodEnd sets field value
func (o *GetCurrentProjectResponse) SetCancelAtPeriodEnd(v float32) {
	o.CancelAtPeriodEnd = v
}

// GetModuleTranslations returns the ModuleTranslations field value
func (o *GetCurrentProjectResponse) GetModuleTranslations() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleTranslations
}

// GetModuleTranslationsOk returns a tuple with the ModuleTranslations field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleTranslationsOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleTranslations, true
}

// SetModuleTranslations sets field value
func (o *GetCurrentProjectResponse) SetModuleTranslations(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleTranslations = v
}

// GetModuleConfigs returns the ModuleConfigs field value
func (o *GetCurrentProjectResponse) GetModuleConfigs() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleConfigs
}

// GetModuleConfigsOk returns a tuple with the ModuleConfigs field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleConfigsOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleConfigs, true
}

// SetModuleConfigs sets field value
func (o *GetCurrentProjectResponse) SetModuleConfigs(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleConfigs = v
}

// GetModuleGates returns the ModuleGates field value
func (o *GetCurrentProjectResponse) GetModuleGates() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleGates
}

// GetModuleGatesOk returns a tuple with the ModuleGates field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleGatesOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleGates, true
}

// SetModuleGates sets field value
func (o *GetCurrentProjectResponse) SetModuleGates(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleGates = v
}

// GetModuleExperiments returns the ModuleExperiments field value
func (o *GetCurrentProjectResponse) GetModuleExperiments() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleExperiments
}

// GetModuleExperimentsOk returns a tuple with the ModuleExperiments field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleExperimentsOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleExperiments, true
}

// SetModuleExperiments sets field value
func (o *GetCurrentProjectResponse) SetModuleExperiments(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleExperiments = v
}

// GetModuleFeedback returns the ModuleFeedback field value
func (o *GetCurrentProjectResponse) GetModuleFeedback() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleFeedback
}

// GetModuleFeedbackOk returns a tuple with the ModuleFeedback field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleFeedbackOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleFeedback, true
}

// SetModuleFeedback sets field value
func (o *GetCurrentProjectResponse) SetModuleFeedback(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleFeedback = v
}

// GetMinSampleSize returns the MinSampleSize field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetMinSampleSize() int32 {
	if o == nil || IsNil(o.MinSampleSize) {
		var ret int32
		return ret
	}
	return *o.MinSampleSize
}

// GetMinSampleSizeOk returns a tuple with the MinSampleSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetMinSampleSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.MinSampleSize) {
		return nil, false
	}
	return o.MinSampleSize, true
}

// HasMinSampleSize returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasMinSampleSize() bool {
	if o != nil && !IsNil(o.MinSampleSize) {
		return true
	}

	return false
}

// SetMinSampleSize gets a reference to the given int32 and assigns it to the MinSampleSize field.
func (o *GetCurrentProjectResponse) SetMinSampleSize(v int32) {
	o.MinSampleSize = &v
}

// GetMinRuntimeDays returns the MinRuntimeDays field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetMinRuntimeDays() int32 {
	if o == nil || IsNil(o.MinRuntimeDays) {
		var ret int32
		return ret
	}
	return *o.MinRuntimeDays
}

// GetMinRuntimeDaysOk returns a tuple with the MinRuntimeDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetMinRuntimeDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.MinRuntimeDays) {
		return nil, false
	}
	return o.MinRuntimeDays, true
}

// HasMinRuntimeDays returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasMinRuntimeDays() bool {
	if o != nil && !IsNil(o.MinRuntimeDays) {
		return true
	}

	return false
}

// SetMinRuntimeDays gets a reference to the given int32 and assigns it to the MinRuntimeDays field.
func (o *GetCurrentProjectResponse) SetMinRuntimeDays(v int32) {
	o.MinRuntimeDays = &v
}

// GetDefaultPower returns the DefaultPower field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetDefaultPower() float32 {
	if o == nil || IsNil(o.DefaultPower) {
		var ret float32
		return ret
	}
	return *o.DefaultPower
}

// GetDefaultPowerOk returns a tuple with the DefaultPower field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetDefaultPowerOk() (*float32, bool) {
	if o == nil || IsNil(o.DefaultPower) {
		return nil, false
	}
	return o.DefaultPower, true
}

// HasDefaultPower returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasDefaultPower() bool {
	if o != nil && !IsNil(o.DefaultPower) {
		return true
	}

	return false
}

// SetDefaultPower gets a reference to the given float32 and assigns it to the DefaultPower field.
func (o *GetCurrentProjectResponse) SetDefaultPower(v float32) {
	o.DefaultPower = &v
}

// GetCiConfidence returns the CiConfidence field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetCiConfidence() float32 {
	if o == nil || IsNil(o.CiConfidence) {
		var ret float32
		return ret
	}
	return *o.CiConfidence
}

// GetCiConfidenceOk returns a tuple with the CiConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCiConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.CiConfidence) {
		return nil, false
	}
	return o.CiConfidence, true
}

// HasCiConfidence returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasCiConfidence() bool {
	if o != nil && !IsNil(o.CiConfidence) {
		return true
	}

	return false
}

// SetCiConfidence gets a reference to the given float32 and assigns it to the CiConfidence field.
func (o *GetCurrentProjectResponse) SetCiConfidence(v float32) {
	o.CiConfidence = &v
}

// GetDefaultAllocationPct returns the DefaultAllocationPct field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetDefaultAllocationPct() int32 {
	if o == nil || IsNil(o.DefaultAllocationPct) {
		var ret int32
		return ret
	}
	return *o.DefaultAllocationPct
}

// GetDefaultAllocationPctOk returns a tuple with the DefaultAllocationPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetDefaultAllocationPctOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultAllocationPct) {
		return nil, false
	}
	return o.DefaultAllocationPct, true
}

// HasDefaultAllocationPct returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasDefaultAllocationPct() bool {
	if o != nil && !IsNil(o.DefaultAllocationPct) {
		return true
	}

	return false
}

// SetDefaultAllocationPct gets a reference to the given int32 and assigns it to the DefaultAllocationPct field.
func (o *GetCurrentProjectResponse) SetDefaultAllocationPct(v int32) {
	o.DefaultAllocationPct = &v
}

// GetDefaultHoldoutBp returns the DefaultHoldoutBp field value
func (o *GetCurrentProjectResponse) GetDefaultHoldoutBp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DefaultHoldoutBp
}

// GetDefaultHoldoutBpOk returns a tuple with the DefaultHoldoutBp field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetDefaultHoldoutBpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultHoldoutBp, true
}

// SetDefaultHoldoutBp sets field value
func (o *GetCurrentProjectResponse) SetDefaultHoldoutBp(v int32) {
	o.DefaultHoldoutBp = v
}

// GetDefaultWinsorizePct returns the DefaultWinsorizePct field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetDefaultWinsorizePct() int32 {
	if o == nil || IsNil(o.DefaultWinsorizePct) {
		var ret int32
		return ret
	}
	return *o.DefaultWinsorizePct
}

// GetDefaultWinsorizePctOk returns a tuple with the DefaultWinsorizePct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetDefaultWinsorizePctOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultWinsorizePct) {
		return nil, false
	}
	return o.DefaultWinsorizePct, true
}

// HasDefaultWinsorizePct returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasDefaultWinsorizePct() bool {
	if o != nil && !IsNil(o.DefaultWinsorizePct) {
		return true
	}

	return false
}

// SetDefaultWinsorizePct gets a reference to the given int32 and assigns it to the DefaultWinsorizePct field.
func (o *GetCurrentProjectResponse) SetDefaultWinsorizePct(v int32) {
	o.DefaultWinsorizePct = &v
}

// GetDefaultMei returns the DefaultMei field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCurrentProjectResponse) GetDefaultMei() float32 {
	if o == nil || IsNil(o.DefaultMei.Get()) {
		var ret float32
		return ret
	}
	return *o.DefaultMei.Get()
}

// GetDefaultMeiOk returns a tuple with the DefaultMei field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDefaultMeiOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultMei.Get(), o.DefaultMei.IsSet()
}

// HasDefaultMei returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasDefaultMei() bool {
	if o != nil && o.DefaultMei.IsSet() {
		return true
	}

	return false
}

// SetDefaultMei gets a reference to the given NullableFloat32 and assigns it to the DefaultMei field.
func (o *GetCurrentProjectResponse) SetDefaultMei(v float32) {
	o.DefaultMei.Set(&v)
}
// SetDefaultMeiNil sets the value for DefaultMei to be an explicit nil
func (o *GetCurrentProjectResponse) SetDefaultMeiNil() {
	o.DefaultMei.Set(nil)
}

// UnsetDefaultMei ensures that no value is present for DefaultMei, not even an explicit nil
func (o *GetCurrentProjectResponse) UnsetDefaultMei() {
	o.DefaultMei.Unset()
}

// GetCupedBaselineDays returns the CupedBaselineDays field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetCupedBaselineDays() int32 {
	if o == nil || IsNil(o.CupedBaselineDays) {
		var ret int32
		return ret
	}
	return *o.CupedBaselineDays
}

// GetCupedBaselineDaysOk returns a tuple with the CupedBaselineDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCupedBaselineDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.CupedBaselineDays) {
		return nil, false
	}
	return o.CupedBaselineDays, true
}

// HasCupedBaselineDays returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasCupedBaselineDays() bool {
	if o != nil && !IsNil(o.CupedBaselineDays) {
		return true
	}

	return false
}

// SetCupedBaselineDays gets a reference to the given int32 and assigns it to the CupedBaselineDays field.
func (o *GetCurrentProjectResponse) SetCupedBaselineDays(v int32) {
	o.CupedBaselineDays = &v
}

// GetCupedMinOverlap returns the CupedMinOverlap field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetCupedMinOverlap() float32 {
	if o == nil || IsNil(o.CupedMinOverlap) {
		var ret float32
		return ret
	}
	return *o.CupedMinOverlap
}

// GetCupedMinOverlapOk returns a tuple with the CupedMinOverlap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCupedMinOverlapOk() (*float32, bool) {
	if o == nil || IsNil(o.CupedMinOverlap) {
		return nil, false
	}
	return o.CupedMinOverlap, true
}

// HasCupedMinOverlap returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasCupedMinOverlap() bool {
	if o != nil && !IsNil(o.CupedMinOverlap) {
		return true
	}

	return false
}

// SetCupedMinOverlap gets a reference to the given float32 and assigns it to the CupedMinOverlap field.
func (o *GetCurrentProjectResponse) SetCupedMinOverlap(v float32) {
	o.CupedMinOverlap = &v
}

// GetCupedMinBaselineUsers returns the CupedMinBaselineUsers field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetCupedMinBaselineUsers() int32 {
	if o == nil || IsNil(o.CupedMinBaselineUsers) {
		var ret int32
		return ret
	}
	return *o.CupedMinBaselineUsers
}

// GetCupedMinBaselineUsersOk returns a tuple with the CupedMinBaselineUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCupedMinBaselineUsersOk() (*int32, bool) {
	if o == nil || IsNil(o.CupedMinBaselineUsers) {
		return nil, false
	}
	return o.CupedMinBaselineUsers, true
}

// HasCupedMinBaselineUsers returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasCupedMinBaselineUsers() bool {
	if o != nil && !IsNil(o.CupedMinBaselineUsers) {
		return true
	}

	return false
}

// SetCupedMinBaselineUsers gets a reference to the given int32 and assigns it to the CupedMinBaselineUsers field.
func (o *GetCurrentProjectResponse) SetCupedMinBaselineUsers(v int32) {
	o.CupedMinBaselineUsers = &v
}

// GetMsprtTauMeiFactor returns the MsprtTauMeiFactor field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetMsprtTauMeiFactor() float32 {
	if o == nil || IsNil(o.MsprtTauMeiFactor) {
		var ret float32
		return ret
	}
	return *o.MsprtTauMeiFactor
}

// GetMsprtTauMeiFactorOk returns a tuple with the MsprtTauMeiFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetMsprtTauMeiFactorOk() (*float32, bool) {
	if o == nil || IsNil(o.MsprtTauMeiFactor) {
		return nil, false
	}
	return o.MsprtTauMeiFactor, true
}

// HasMsprtTauMeiFactor returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasMsprtTauMeiFactor() bool {
	if o != nil && !IsNil(o.MsprtTauMeiFactor) {
		return true
	}

	return false
}

// SetMsprtTauMeiFactor gets a reference to the given float32 and assigns it to the MsprtTauMeiFactor field.
func (o *GetCurrentProjectResponse) SetMsprtTauMeiFactor(v float32) {
	o.MsprtTauMeiFactor = &v
}

// GetMsprtTauSdFactor returns the MsprtTauSdFactor field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetMsprtTauSdFactor() float32 {
	if o == nil || IsNil(o.MsprtTauSdFactor) {
		var ret float32
		return ret
	}
	return *o.MsprtTauSdFactor
}

// GetMsprtTauSdFactorOk returns a tuple with the MsprtTauSdFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetMsprtTauSdFactorOk() (*float32, bool) {
	if o == nil || IsNil(o.MsprtTauSdFactor) {
		return nil, false
	}
	return o.MsprtTauSdFactor, true
}

// HasMsprtTauSdFactor returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasMsprtTauSdFactor() bool {
	if o != nil && !IsNil(o.MsprtTauSdFactor) {
		return true
	}

	return false
}

// SetMsprtTauSdFactor gets a reference to the given float32 and assigns it to the MsprtTauSdFactor field.
func (o *GetCurrentProjectResponse) SetMsprtTauSdFactor(v float32) {
	o.MsprtTauSdFactor = &v
}

// GetSrmThreshold returns the SrmThreshold field value if set, zero value otherwise.
func (o *GetCurrentProjectResponse) GetSrmThreshold() float32 {
	if o == nil || IsNil(o.SrmThreshold) {
		var ret float32
		return ret
	}
	return *o.SrmThreshold
}

// GetSrmThresholdOk returns a tuple with the SrmThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetSrmThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.SrmThreshold) {
		return nil, false
	}
	return o.SrmThreshold, true
}

// HasSrmThreshold returns a boolean if a field has been set.
func (o *GetCurrentProjectResponse) HasSrmThreshold() bool {
	if o != nil && !IsNil(o.SrmThreshold) {
		return true
	}

	return false
}

// SetSrmThreshold gets a reference to the given float32 and assigns it to the SrmThreshold field.
func (o *GetCurrentProjectResponse) SetSrmThreshold(v float32) {
	o.SrmThreshold = &v
}

// GetSlug returns the Slug field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetSlug() string {
	if o == nil || o.Slug.Get() == nil {
		var ret string
		return ret
	}

	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// SetSlug sets field value
func (o *GetCurrentProjectResponse) SetSlug(v string) {
	o.Slug.Set(&v)
}

// GetLogo returns the Logo field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetLogo() string {
	if o == nil || o.Logo.Get() == nil {
		var ret string
		return ret
	}

	return *o.Logo.Get()
}

// GetLogoOk returns a tuple with the Logo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logo.Get(), o.Logo.IsSet()
}

// SetLogo sets field value
func (o *GetCurrentProjectResponse) SetLogo(v string) {
	o.Logo.Set(&v)
}

// GetDefaultEnv returns the DefaultEnv field value
func (o *GetCurrentProjectResponse) GetDefaultEnv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultEnv
}

// GetDefaultEnvOk returns a tuple with the DefaultEnv field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetDefaultEnvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultEnv, true
}

// SetDefaultEnv sets field value
func (o *GetCurrentProjectResponse) SetDefaultEnv(v string) {
	o.DefaultEnv = v
}

// GetTimezone returns the Timezone field value
func (o *GetCurrentProjectResponse) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *GetCurrentProjectResponse) SetTimezone(v string) {
	o.Timezone = v
}

// GetStatMethod returns the StatMethod field value
func (o *GetCurrentProjectResponse) GetStatMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatMethod
}

// GetStatMethodOk returns a tuple with the StatMethod field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetStatMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatMethod, true
}

// SetStatMethod sets field value
func (o *GetCurrentProjectResponse) SetStatMethod(v string) {
	o.StatMethod = v
}

// GetSigThreshold returns the SigThreshold field value
func (o *GetCurrentProjectResponse) GetSigThreshold() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigThreshold
}

// GetSigThresholdOk returns a tuple with the SigThreshold field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetSigThresholdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigThreshold, true
}

// SetSigThreshold sets field value
func (o *GetCurrentProjectResponse) SetSigThreshold(v string) {
	o.SigThreshold = v
}

// GetAutoRollback returns the AutoRollback field value
func (o *GetCurrentProjectResponse) GetAutoRollback() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoRollback
}

// GetAutoRollbackOk returns a tuple with the AutoRollback field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetAutoRollbackOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoRollback, true
}

// SetAutoRollback sets field value
func (o *GetCurrentProjectResponse) SetAutoRollback(v bool) {
	o.AutoRollback = v
}

// GetMinSampleDays returns the MinSampleDays field value
func (o *GetCurrentProjectResponse) GetMinSampleDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinSampleDays
}

// GetMinSampleDaysOk returns a tuple with the MinSampleDays field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetMinSampleDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinSampleDays, true
}

// SetMinSampleDays sets field value
func (o *GetCurrentProjectResponse) SetMinSampleDays(v int32) {
	o.MinSampleDays = v
}

// GetModuleUser returns the ModuleUser field value
func (o *GetCurrentProjectResponse) GetModuleUser() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleUser
}

// GetModuleUserOk returns a tuple with the ModuleUser field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleUserOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleUser, true
}

// SetModuleUser sets field value
func (o *GetCurrentProjectResponse) SetModuleUser(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleUser = v
}

// GetModuleEvents returns the ModuleEvents field value
func (o *GetCurrentProjectResponse) GetModuleEvents() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.ModuleEvents
}

// GetModuleEventsOk returns a tuple with the ModuleEvents field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetModuleEventsOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModuleEvents, true
}

// SetModuleEvents sets field value
func (o *GetCurrentProjectResponse) SetModuleEvents(v GetCurrentProjectResponseModuleTranslations) {
	o.ModuleEvents = v
}

// GetAllowPublicTickets returns the AllowPublicTickets field value
func (o *GetCurrentProjectResponse) GetAllowPublicTickets() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.AllowPublicTickets
}

// GetAllowPublicTicketsOk returns a tuple with the AllowPublicTickets field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetAllowPublicTicketsOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowPublicTickets, true
}

// SetAllowPublicTickets sets field value
func (o *GetCurrentProjectResponse) SetAllowPublicTickets(v GetCurrentProjectResponseModuleTranslations) {
	o.AllowPublicTickets = v
}

// GetErrorAutocloseDays returns the ErrorAutocloseDays field value
func (o *GetCurrentProjectResponse) GetErrorAutocloseDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorAutocloseDays
}

// GetErrorAutocloseDaysOk returns a tuple with the ErrorAutocloseDays field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetErrorAutocloseDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorAutocloseDays, true
}

// SetErrorAutocloseDays sets field value
func (o *GetCurrentProjectResponse) SetErrorAutocloseDays(v int32) {
	o.ErrorAutocloseDays = v
}

// GetErrorTicketMinOccurrences returns the ErrorTicketMinOccurrences field value
func (o *GetCurrentProjectResponse) GetErrorTicketMinOccurrences() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorTicketMinOccurrences
}

// GetErrorTicketMinOccurrencesOk returns a tuple with the ErrorTicketMinOccurrences field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetErrorTicketMinOccurrencesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorTicketMinOccurrences, true
}

// SetErrorTicketMinOccurrences sets field value
func (o *GetCurrentProjectResponse) SetErrorTicketMinOccurrences(v int32) {
	o.ErrorTicketMinOccurrences = v
}

// GetStripeSubscriptionId returns the StripeSubscriptionId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetStripeSubscriptionId() string {
	if o == nil || o.StripeSubscriptionId.Get() == nil {
		var ret string
		return ret
	}

	return *o.StripeSubscriptionId.Get()
}

// GetStripeSubscriptionIdOk returns a tuple with the StripeSubscriptionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetStripeSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeSubscriptionId.Get(), o.StripeSubscriptionId.IsSet()
}

// SetStripeSubscriptionId sets field value
func (o *GetCurrentProjectResponse) SetStripeSubscriptionId(v string) {
	o.StripeSubscriptionId.Set(&v)
}

// GetScheduledInterval returns the ScheduledInterval field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetScheduledInterval() string {
	if o == nil || o.ScheduledInterval.Get() == nil {
		var ret string
		return ret
	}

	return *o.ScheduledInterval.Get()
}

// GetScheduledIntervalOk returns a tuple with the ScheduledInterval field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetScheduledIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScheduledInterval.Get(), o.ScheduledInterval.IsSet()
}

// SetScheduledInterval sets field value
func (o *GetCurrentProjectResponse) SetScheduledInterval(v string) {
	o.ScheduledInterval.Set(&v)
}

// GetSpendLimitEnabled returns the SpendLimitEnabled field value
func (o *GetCurrentProjectResponse) GetSpendLimitEnabled() GetCurrentProjectResponseModuleTranslations {
	if o == nil {
		var ret GetCurrentProjectResponseModuleTranslations
		return ret
	}

	return o.SpendLimitEnabled
}

// GetSpendLimitEnabledOk returns a tuple with the SpendLimitEnabled field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetSpendLimitEnabledOk() (*GetCurrentProjectResponseModuleTranslations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpendLimitEnabled, true
}

// SetSpendLimitEnabled sets field value
func (o *GetCurrentProjectResponse) SetSpendLimitEnabled(v GetCurrentProjectResponseModuleTranslations) {
	o.SpendLimitEnabled = v
}

// GetSpendLimitUsd returns the SpendLimitUsd field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *GetCurrentProjectResponse) GetSpendLimitUsd() int32 {
	if o == nil || o.SpendLimitUsd.Get() == nil {
		var ret int32
		return ret
	}

	return *o.SpendLimitUsd.Get()
}

// GetSpendLimitUsdOk returns a tuple with the SpendLimitUsd field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetSpendLimitUsdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpendLimitUsd.Get(), o.SpendLimitUsd.IsSet()
}

// SetSpendLimitUsd sets field value
func (o *GetCurrentProjectResponse) SetSpendLimitUsd(v int32) {
	o.SpendLimitUsd.Set(&v)
}

// GetSpendAlertEmail returns the SpendAlertEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetSpendAlertEmail() string {
	if o == nil || o.SpendAlertEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.SpendAlertEmail.Get()
}

// GetSpendAlertEmailOk returns a tuple with the SpendAlertEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetSpendAlertEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpendAlertEmail.Get(), o.SpendAlertEmail.IsSet()
}

// SetSpendAlertEmail sets field value
func (o *GetCurrentProjectResponse) SetSpendAlertEmail(v string) {
	o.SpendAlertEmail.Set(&v)
}

// GetDefaultAssigneePendingApproval returns the DefaultAssigneePendingApproval field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneePendingApproval() string {
	if o == nil || o.DefaultAssigneePendingApproval.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultAssigneePendingApproval.Get()
}

// GetDefaultAssigneePendingApprovalOk returns a tuple with the DefaultAssigneePendingApproval field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneePendingApprovalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAssigneePendingApproval.Get(), o.DefaultAssigneePendingApproval.IsSet()
}

// SetDefaultAssigneePendingApproval sets field value
func (o *GetCurrentProjectResponse) SetDefaultAssigneePendingApproval(v string) {
	o.DefaultAssigneePendingApproval.Set(&v)
}

// GetDefaultAssigneeConnectorPendingApproval returns the DefaultAssigneeConnectorPendingApproval field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeConnectorPendingApproval() string {
	if o == nil || o.DefaultAssigneeConnectorPendingApproval.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultAssigneeConnectorPendingApproval.Get()
}

// GetDefaultAssigneeConnectorPendingApprovalOk returns a tuple with the DefaultAssigneeConnectorPendingApproval field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeConnectorPendingApprovalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAssigneeConnectorPendingApproval.Get(), o.DefaultAssigneeConnectorPendingApproval.IsSet()
}

// SetDefaultAssigneeConnectorPendingApproval sets field value
func (o *GetCurrentProjectResponse) SetDefaultAssigneeConnectorPendingApproval(v string) {
	o.DefaultAssigneeConnectorPendingApproval.Set(&v)
}

// GetDefaultAssigneeOpen returns the DefaultAssigneeOpen field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeOpen() string {
	if o == nil || o.DefaultAssigneeOpen.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultAssigneeOpen.Get()
}

// GetDefaultAssigneeOpenOk returns a tuple with the DefaultAssigneeOpen field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeOpenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAssigneeOpen.Get(), o.DefaultAssigneeOpen.IsSet()
}

// SetDefaultAssigneeOpen sets field value
func (o *GetCurrentProjectResponse) SetDefaultAssigneeOpen(v string) {
	o.DefaultAssigneeOpen.Set(&v)
}

// GetDefaultAssigneeConnectorOpen returns the DefaultAssigneeConnectorOpen field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeConnectorOpen() string {
	if o == nil || o.DefaultAssigneeConnectorOpen.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultAssigneeConnectorOpen.Get()
}

// GetDefaultAssigneeConnectorOpenOk returns a tuple with the DefaultAssigneeConnectorOpen field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDefaultAssigneeConnectorOpenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAssigneeConnectorOpen.Get(), o.DefaultAssigneeConnectorOpen.IsSet()
}

// SetDefaultAssigneeConnectorOpen sets field value
func (o *GetCurrentProjectResponse) SetDefaultAssigneeConnectorOpen(v string) {
	o.DefaultAssigneeConnectorOpen.Set(&v)
}

// GetDeletedAt returns the DeletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCurrentProjectResponse) GetDeletedAt() string {
	if o == nil || o.DeletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentProjectResponse) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// SetDeletedAt sets field value
func (o *GetCurrentProjectResponse) SetDeletedAt(v string) {
	o.DeletedAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetCurrentProjectResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetCurrentProjectResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetCurrentProjectResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetCurrentProjectResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o GetCurrentProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["domain"] = o.Domain.Get()
	toSerialize["ownerEmail"] = o.OwnerEmail
	toSerialize["plan"] = o.Plan
	toSerialize["status"] = o.Status
	toSerialize["subscriptionStatus"] = o.SubscriptionStatus
	toSerialize["billingInterval"] = o.BillingInterval
	toSerialize["currentPeriodEnd"] = o.CurrentPeriodEnd.Get()
	toSerialize["trialEndsAt"] = o.TrialEndsAt.Get()
	toSerialize["cancelAtPeriodEnd"] = o.CancelAtPeriodEnd
	toSerialize["moduleTranslations"] = o.ModuleTranslations
	toSerialize["moduleConfigs"] = o.ModuleConfigs
	toSerialize["moduleGates"] = o.ModuleGates
	toSerialize["moduleExperiments"] = o.ModuleExperiments
	toSerialize["moduleFeedback"] = o.ModuleFeedback
	if !IsNil(o.MinSampleSize) {
		toSerialize["minSampleSize"] = o.MinSampleSize
	}
	if !IsNil(o.MinRuntimeDays) {
		toSerialize["minRuntimeDays"] = o.MinRuntimeDays
	}
	if !IsNil(o.DefaultPower) {
		toSerialize["defaultPower"] = o.DefaultPower
	}
	if !IsNil(o.CiConfidence) {
		toSerialize["ciConfidence"] = o.CiConfidence
	}
	if !IsNil(o.DefaultAllocationPct) {
		toSerialize["defaultAllocationPct"] = o.DefaultAllocationPct
	}
	toSerialize["defaultHoldoutBp"] = o.DefaultHoldoutBp
	if !IsNil(o.DefaultWinsorizePct) {
		toSerialize["defaultWinsorizePct"] = o.DefaultWinsorizePct
	}
	if o.DefaultMei.IsSet() {
		toSerialize["defaultMei"] = o.DefaultMei.Get()
	}
	if !IsNil(o.CupedBaselineDays) {
		toSerialize["cupedBaselineDays"] = o.CupedBaselineDays
	}
	if !IsNil(o.CupedMinOverlap) {
		toSerialize["cupedMinOverlap"] = o.CupedMinOverlap
	}
	if !IsNil(o.CupedMinBaselineUsers) {
		toSerialize["cupedMinBaselineUsers"] = o.CupedMinBaselineUsers
	}
	if !IsNil(o.MsprtTauMeiFactor) {
		toSerialize["msprtTauMeiFactor"] = o.MsprtTauMeiFactor
	}
	if !IsNil(o.MsprtTauSdFactor) {
		toSerialize["msprtTauSdFactor"] = o.MsprtTauSdFactor
	}
	if !IsNil(o.SrmThreshold) {
		toSerialize["srmThreshold"] = o.SrmThreshold
	}
	toSerialize["slug"] = o.Slug.Get()
	toSerialize["logo"] = o.Logo.Get()
	toSerialize["defaultEnv"] = o.DefaultEnv
	toSerialize["timezone"] = o.Timezone
	toSerialize["statMethod"] = o.StatMethod
	toSerialize["sigThreshold"] = o.SigThreshold
	toSerialize["autoRollback"] = o.AutoRollback
	toSerialize["minSampleDays"] = o.MinSampleDays
	toSerialize["moduleUser"] = o.ModuleUser
	toSerialize["moduleEvents"] = o.ModuleEvents
	toSerialize["allowPublicTickets"] = o.AllowPublicTickets
	toSerialize["errorAutocloseDays"] = o.ErrorAutocloseDays
	toSerialize["errorTicketMinOccurrences"] = o.ErrorTicketMinOccurrences
	toSerialize["stripeSubscriptionId"] = o.StripeSubscriptionId.Get()
	toSerialize["scheduledInterval"] = o.ScheduledInterval.Get()
	toSerialize["spendLimitEnabled"] = o.SpendLimitEnabled
	toSerialize["spendLimitUsd"] = o.SpendLimitUsd.Get()
	toSerialize["spendAlertEmail"] = o.SpendAlertEmail.Get()
	toSerialize["defaultAssigneePendingApproval"] = o.DefaultAssigneePendingApproval.Get()
	toSerialize["defaultAssigneeConnectorPendingApproval"] = o.DefaultAssigneeConnectorPendingApproval.Get()
	toSerialize["defaultAssigneeOpen"] = o.DefaultAssigneeOpen.Get()
	toSerialize["defaultAssigneeConnectorOpen"] = o.DefaultAssigneeConnectorOpen.Get()
	toSerialize["deletedAt"] = o.DeletedAt.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCurrentProjectResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"domain",
		"ownerEmail",
		"plan",
		"status",
		"subscriptionStatus",
		"billingInterval",
		"currentPeriodEnd",
		"trialEndsAt",
		"cancelAtPeriodEnd",
		"moduleTranslations",
		"moduleConfigs",
		"moduleGates",
		"moduleExperiments",
		"moduleFeedback",
		"defaultHoldoutBp",
		"slug",
		"logo",
		"defaultEnv",
		"timezone",
		"statMethod",
		"sigThreshold",
		"autoRollback",
		"minSampleDays",
		"moduleUser",
		"moduleEvents",
		"allowPublicTickets",
		"errorAutocloseDays",
		"errorTicketMinOccurrences",
		"stripeSubscriptionId",
		"scheduledInterval",
		"spendLimitEnabled",
		"spendLimitUsd",
		"spendAlertEmail",
		"defaultAssigneePendingApproval",
		"defaultAssigneeConnectorPendingApproval",
		"defaultAssigneeOpen",
		"defaultAssigneeConnectorOpen",
		"deletedAt",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCurrentProjectResponse := _GetCurrentProjectResponse{}

	err = json.Unmarshal(data, &varGetCurrentProjectResponse)

	if err != nil {
		return err
	}

	*o = GetCurrentProjectResponse(varGetCurrentProjectResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "ownerEmail")
		delete(additionalProperties, "plan")
		delete(additionalProperties, "status")
		delete(additionalProperties, "subscriptionStatus")
		delete(additionalProperties, "billingInterval")
		delete(additionalProperties, "currentPeriodEnd")
		delete(additionalProperties, "trialEndsAt")
		delete(additionalProperties, "cancelAtPeriodEnd")
		delete(additionalProperties, "moduleTranslations")
		delete(additionalProperties, "moduleConfigs")
		delete(additionalProperties, "moduleGates")
		delete(additionalProperties, "moduleExperiments")
		delete(additionalProperties, "moduleFeedback")
		delete(additionalProperties, "minSampleSize")
		delete(additionalProperties, "minRuntimeDays")
		delete(additionalProperties, "defaultPower")
		delete(additionalProperties, "ciConfidence")
		delete(additionalProperties, "defaultAllocationPct")
		delete(additionalProperties, "defaultHoldoutBp")
		delete(additionalProperties, "defaultWinsorizePct")
		delete(additionalProperties, "defaultMei")
		delete(additionalProperties, "cupedBaselineDays")
		delete(additionalProperties, "cupedMinOverlap")
		delete(additionalProperties, "cupedMinBaselineUsers")
		delete(additionalProperties, "msprtTauMeiFactor")
		delete(additionalProperties, "msprtTauSdFactor")
		delete(additionalProperties, "srmThreshold")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "logo")
		delete(additionalProperties, "defaultEnv")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "statMethod")
		delete(additionalProperties, "sigThreshold")
		delete(additionalProperties, "autoRollback")
		delete(additionalProperties, "minSampleDays")
		delete(additionalProperties, "moduleUser")
		delete(additionalProperties, "moduleEvents")
		delete(additionalProperties, "allowPublicTickets")
		delete(additionalProperties, "errorAutocloseDays")
		delete(additionalProperties, "errorTicketMinOccurrences")
		delete(additionalProperties, "stripeSubscriptionId")
		delete(additionalProperties, "scheduledInterval")
		delete(additionalProperties, "spendLimitEnabled")
		delete(additionalProperties, "spendLimitUsd")
		delete(additionalProperties, "spendAlertEmail")
		delete(additionalProperties, "defaultAssigneePendingApproval")
		delete(additionalProperties, "defaultAssigneeConnectorPendingApproval")
		delete(additionalProperties, "defaultAssigneeOpen")
		delete(additionalProperties, "defaultAssigneeConnectorOpen")
		delete(additionalProperties, "deletedAt")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCurrentProjectResponse struct {
	value *GetCurrentProjectResponse
	isSet bool
}

func (v NullableGetCurrentProjectResponse) Get() *GetCurrentProjectResponse {
	return v.value
}

func (v *NullableGetCurrentProjectResponse) Set(val *GetCurrentProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentProjectResponse(val *GetCurrentProjectResponse) *NullableGetCurrentProjectResponse {
	return &NullableGetCurrentProjectResponse{value: val, isSet: true}
}

func (v NullableGetCurrentProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


