/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateUniverseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUniverseResponse{}

// UpdateUniverseResponse struct for UpdateUniverseResponse
type UpdateUniverseResponse struct {
	// Universe id that was updated.
	Id string `json:"id"`
}

type _UpdateUniverseResponse UpdateUniverseResponse

// NewUpdateUniverseResponse instantiates a new UpdateUniverseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUniverseResponse(id string) *UpdateUniverseResponse {
	this := UpdateUniverseResponse{}
	this.Id = id
	return &this
}

// NewUpdateUniverseResponseWithDefaults instantiates a new UpdateUniverseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUniverseResponseWithDefaults() *UpdateUniverseResponse {
	this := UpdateUniverseResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateUniverseResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateUniverseResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateUniverseResponse) SetId(v string) {
	o.Id = v
}

func (o UpdateUniverseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUniverseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *UpdateUniverseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateUniverseResponse := _UpdateUniverseResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateUniverseResponse)

	if err != nil {
		return err
	}

	*o = UpdateUniverseResponse(varUpdateUniverseResponse)

	return err
}

type NullableUpdateUniverseResponse struct {
	value *UpdateUniverseResponse
	isSet bool
}

func (v NullableUpdateUniverseResponse) Get() *UpdateUniverseResponse {
	return v.value
}

func (v *NullableUpdateUniverseResponse) Set(val *UpdateUniverseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUniverseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUniverseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUniverseResponse(val *UpdateUniverseResponse) *NullableUpdateUniverseResponse {
	return &NullableUpdateUniverseResponse{value: val, isSet: true}
}

func (v NullableUpdateUniverseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUniverseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


