/*
Shipeasy Admin API (server-SDK surface)

The slice of the Shipeasy admin API that the published server SDKs expose as their optional `AdminClient`. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Three capabilities, nothing else:  - **File a public ticket** — a bug or a feature request onto the project's ops queue. - **Toggle a kill switch** — flip the switch itself, or one of its named sub-switches, on one environment. - **Manage a flag's whitelist** — read, replace, add to, or remove from the allowlist that admits specific identities ahead of every targeting rule.  Everything else in the admin API is reachable through the Shipeasy CLI and MCP server, which speak the complete contract (`openapi.yaml`).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePublicBugRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePublicBugRequest{}

// CreatePublicBugRequest Body for `POST /ops/bug`. The same bug fields as `CreateBugRequest`, minus the `type` discriminator — the path already says what is being filed.
type CreatePublicBugRequest struct {
	// One-line bug title (no leading/trailing whitespace).
	Title string `json:"title" validate:"regexp=^\\\\S(.*\\\\S)?$"`
	// How to reproduce the bug.
	StepsToReproduce *string `json:"stepsToReproduce,omitempty"`
	// What actually happened.
	ActualResult *string `json:"actualResult,omitempty"`
	// What was expected instead.
	ExpectedResult *string `json:"expectedResult,omitempty"`
	// Initial triage priority, or `null`.
	Priority NullableOpsItemPriority `json:"priority,omitempty"`
	// Initial lifecycle status; defaults to `open` when omitted.
	Status *OpsItemStatus `json:"status,omitempty"`
	// The `users.id` of the person to assign as owner at creation, or `null`.
	AssigneeId NullableString `json:"assigneeId,omitempty"`
	// Emails of teammates to subscribe to this item's Slack pings at creation.
	Subscribers []string `json:"subscribers,omitempty"`
	// Tag names to attach at creation (get-or-created by name, deduped case-insensitively).
	Tags []string `json:"tags,omitempty"`
	// Email of the reporter, or `null`.
	ReporterEmail NullableString `json:"reporterEmail,omitempty"`
	// URL of the page the bug relates to, or `null`.
	PageUrl NullableString `json:"pageUrl,omitempty"`
	// Reporter's user-agent string, or `null`.
	UserAgent NullableString `json:"userAgent,omitempty"`
	// Reporter's viewport (e.g. `1280x720`), or `null`.
	Viewport NullableString `json:"viewport,omitempty"`
	// Arbitrary capture context, or `null`.
	Context map[string]interface{} `json:"context,omitempty"`
	// Where this bug's completion notification lands.
	Notify NullableNotificationTarget `json:"notify,omitempty"`
}

type _CreatePublicBugRequest CreatePublicBugRequest

// NewCreatePublicBugRequest instantiates a new CreatePublicBugRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePublicBugRequest(title string) *CreatePublicBugRequest {
	this := CreatePublicBugRequest{}
	this.Title = title
	var stepsToReproduce string = ""
	this.StepsToReproduce = &stepsToReproduce
	var actualResult string = ""
	this.ActualResult = &actualResult
	var expectedResult string = ""
	this.ExpectedResult = &expectedResult
	return &this
}

// NewCreatePublicBugRequestWithDefaults instantiates a new CreatePublicBugRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePublicBugRequestWithDefaults() *CreatePublicBugRequest {
	this := CreatePublicBugRequest{}
	var stepsToReproduce string = ""
	this.StepsToReproduce = &stepsToReproduce
	var actualResult string = ""
	this.ActualResult = &actualResult
	var expectedResult string = ""
	this.ExpectedResult = &expectedResult
	return &this
}

// GetTitle returns the Title field value
func (o *CreatePublicBugRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreatePublicBugRequest) SetTitle(v string) {
	o.Title = v
}

// GetStepsToReproduce returns the StepsToReproduce field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetStepsToReproduce() string {
	if o == nil || IsNil(o.StepsToReproduce) {
		var ret string
		return ret
	}
	return *o.StepsToReproduce
}

// GetStepsToReproduceOk returns a tuple with the StepsToReproduce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetStepsToReproduceOk() (*string, bool) {
	if o == nil || IsNil(o.StepsToReproduce) {
		return nil, false
	}
	return o.StepsToReproduce, true
}

// HasStepsToReproduce returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasStepsToReproduce() bool {
	if o != nil && !IsNil(o.StepsToReproduce) {
		return true
	}

	return false
}

// SetStepsToReproduce gets a reference to the given string and assigns it to the StepsToReproduce field.
func (o *CreatePublicBugRequest) SetStepsToReproduce(v string) {
	o.StepsToReproduce = &v
}

// GetActualResult returns the ActualResult field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetActualResult() string {
	if o == nil || IsNil(o.ActualResult) {
		var ret string
		return ret
	}
	return *o.ActualResult
}

// GetActualResultOk returns a tuple with the ActualResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetActualResultOk() (*string, bool) {
	if o == nil || IsNil(o.ActualResult) {
		return nil, false
	}
	return o.ActualResult, true
}

// HasActualResult returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasActualResult() bool {
	if o != nil && !IsNil(o.ActualResult) {
		return true
	}

	return false
}

// SetActualResult gets a reference to the given string and assigns it to the ActualResult field.
func (o *CreatePublicBugRequest) SetActualResult(v string) {
	o.ActualResult = &v
}

// GetExpectedResult returns the ExpectedResult field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetExpectedResult() string {
	if o == nil || IsNil(o.ExpectedResult) {
		var ret string
		return ret
	}
	return *o.ExpectedResult
}

// GetExpectedResultOk returns a tuple with the ExpectedResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetExpectedResultOk() (*string, bool) {
	if o == nil || IsNil(o.ExpectedResult) {
		return nil, false
	}
	return o.ExpectedResult, true
}

// HasExpectedResult returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasExpectedResult() bool {
	if o != nil && !IsNil(o.ExpectedResult) {
		return true
	}

	return false
}

// SetExpectedResult gets a reference to the given string and assigns it to the ExpectedResult field.
func (o *CreatePublicBugRequest) SetExpectedResult(v string) {
	o.ExpectedResult = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetPriority() OpsItemPriority {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret OpsItemPriority
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetPriorityOk() (*OpsItemPriority, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableOpsItemPriority and assigns it to the Priority field.
func (o *CreatePublicBugRequest) SetPriority(v OpsItemPriority) {
	o.Priority.Set(&v)
}
// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *CreatePublicBugRequest) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetPriority() {
	o.Priority.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetStatus() OpsItemStatus {
	if o == nil || IsNil(o.Status) {
		var ret OpsItemStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetStatusOk() (*OpsItemStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OpsItemStatus and assigns it to the Status field.
func (o *CreatePublicBugRequest) SetStatus(v OpsItemStatus) {
	o.Status = &v
}

// GetAssigneeId returns the AssigneeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetAssigneeId() string {
	if o == nil || IsNil(o.AssigneeId.Get()) {
		var ret string
		return ret
	}
	return *o.AssigneeId.Get()
}

// GetAssigneeIdOk returns a tuple with the AssigneeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetAssigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssigneeId.Get(), o.AssigneeId.IsSet()
}

// HasAssigneeId returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasAssigneeId() bool {
	if o != nil && o.AssigneeId.IsSet() {
		return true
	}

	return false
}

// SetAssigneeId gets a reference to the given NullableString and assigns it to the AssigneeId field.
func (o *CreatePublicBugRequest) SetAssigneeId(v string) {
	o.AssigneeId.Set(&v)
}
// SetAssigneeIdNil sets the value for AssigneeId to be an explicit nil
func (o *CreatePublicBugRequest) SetAssigneeIdNil() {
	o.AssigneeId.Set(nil)
}

// UnsetAssigneeId ensures that no value is present for AssigneeId, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetAssigneeId() {
	o.AssigneeId.Unset()
}

// GetSubscribers returns the Subscribers field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetSubscribers() []string {
	if o == nil || IsNil(o.Subscribers) {
		var ret []string
		return ret
	}
	return o.Subscribers
}

// GetSubscribersOk returns a tuple with the Subscribers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetSubscribersOk() ([]string, bool) {
	if o == nil || IsNil(o.Subscribers) {
		return nil, false
	}
	return o.Subscribers, true
}

// HasSubscribers returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasSubscribers() bool {
	if o != nil && !IsNil(o.Subscribers) {
		return true
	}

	return false
}

// SetSubscribers gets a reference to the given []string and assigns it to the Subscribers field.
func (o *CreatePublicBugRequest) SetSubscribers(v []string) {
	o.Subscribers = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreatePublicBugRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePublicBugRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreatePublicBugRequest) SetTags(v []string) {
	o.Tags = v
}

// GetReporterEmail returns the ReporterEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetReporterEmail() string {
	if o == nil || IsNil(o.ReporterEmail.Get()) {
		var ret string
		return ret
	}
	return *o.ReporterEmail.Get()
}

// GetReporterEmailOk returns a tuple with the ReporterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetReporterEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReporterEmail.Get(), o.ReporterEmail.IsSet()
}

// HasReporterEmail returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasReporterEmail() bool {
	if o != nil && o.ReporterEmail.IsSet() {
		return true
	}

	return false
}

// SetReporterEmail gets a reference to the given NullableString and assigns it to the ReporterEmail field.
func (o *CreatePublicBugRequest) SetReporterEmail(v string) {
	o.ReporterEmail.Set(&v)
}
// SetReporterEmailNil sets the value for ReporterEmail to be an explicit nil
func (o *CreatePublicBugRequest) SetReporterEmailNil() {
	o.ReporterEmail.Set(nil)
}

// UnsetReporterEmail ensures that no value is present for ReporterEmail, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetReporterEmail() {
	o.ReporterEmail.Unset()
}

// GetPageUrl returns the PageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetPageUrl() string {
	if o == nil || IsNil(o.PageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PageUrl.Get()
}

// GetPageUrlOk returns a tuple with the PageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageUrl.Get(), o.PageUrl.IsSet()
}

// HasPageUrl returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasPageUrl() bool {
	if o != nil && o.PageUrl.IsSet() {
		return true
	}

	return false
}

// SetPageUrl gets a reference to the given NullableString and assigns it to the PageUrl field.
func (o *CreatePublicBugRequest) SetPageUrl(v string) {
	o.PageUrl.Set(&v)
}
// SetPageUrlNil sets the value for PageUrl to be an explicit nil
func (o *CreatePublicBugRequest) SetPageUrlNil() {
	o.PageUrl.Set(nil)
}

// UnsetPageUrl ensures that no value is present for PageUrl, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetPageUrl() {
	o.PageUrl.Unset()
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent.Get()) {
		var ret string
		return ret
	}
	return *o.UserAgent.Get()
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserAgent.Get(), o.UserAgent.IsSet()
}

// HasUserAgent returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasUserAgent() bool {
	if o != nil && o.UserAgent.IsSet() {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given NullableString and assigns it to the UserAgent field.
func (o *CreatePublicBugRequest) SetUserAgent(v string) {
	o.UserAgent.Set(&v)
}
// SetUserAgentNil sets the value for UserAgent to be an explicit nil
func (o *CreatePublicBugRequest) SetUserAgentNil() {
	o.UserAgent.Set(nil)
}

// UnsetUserAgent ensures that no value is present for UserAgent, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetUserAgent() {
	o.UserAgent.Unset()
}

// GetViewport returns the Viewport field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetViewport() string {
	if o == nil || IsNil(o.Viewport.Get()) {
		var ret string
		return ret
	}
	return *o.Viewport.Get()
}

// GetViewportOk returns a tuple with the Viewport field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetViewportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Viewport.Get(), o.Viewport.IsSet()
}

// HasViewport returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasViewport() bool {
	if o != nil && o.Viewport.IsSet() {
		return true
	}

	return false
}

// SetViewport gets a reference to the given NullableString and assigns it to the Viewport field.
func (o *CreatePublicBugRequest) SetViewport(v string) {
	o.Viewport.Set(&v)
}
// SetViewportNil sets the value for Viewport to be an explicit nil
func (o *CreatePublicBugRequest) SetViewportNil() {
	o.Viewport.Set(nil)
}

// UnsetViewport ensures that no value is present for Viewport, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetViewport() {
	o.Viewport.Unset()
}

// GetContext returns the Context field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetContext() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return map[string]interface{}{}, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *CreatePublicBugRequest) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetNotify returns the Notify field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePublicBugRequest) GetNotify() NotificationTarget {
	if o == nil || IsNil(o.Notify.Get()) {
		var ret NotificationTarget
		return ret
	}
	return *o.Notify.Get()
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePublicBugRequest) GetNotifyOk() (*NotificationTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notify.Get(), o.Notify.IsSet()
}

// HasNotify returns a boolean if a field has been set.
func (o *CreatePublicBugRequest) HasNotify() bool {
	if o != nil && o.Notify.IsSet() {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NullableNotificationTarget and assigns it to the Notify field.
func (o *CreatePublicBugRequest) SetNotify(v NotificationTarget) {
	o.Notify.Set(&v)
}
// SetNotifyNil sets the value for Notify to be an explicit nil
func (o *CreatePublicBugRequest) SetNotifyNil() {
	o.Notify.Set(nil)
}

// UnsetNotify ensures that no value is present for Notify, not even an explicit nil
func (o *CreatePublicBugRequest) UnsetNotify() {
	o.Notify.Unset()
}

func (o CreatePublicBugRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePublicBugRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.StepsToReproduce) {
		toSerialize["stepsToReproduce"] = o.StepsToReproduce
	}
	if !IsNil(o.ActualResult) {
		toSerialize["actualResult"] = o.ActualResult
	}
	if !IsNil(o.ExpectedResult) {
		toSerialize["expectedResult"] = o.ExpectedResult
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.AssigneeId.IsSet() {
		toSerialize["assigneeId"] = o.AssigneeId.Get()
	}
	if !IsNil(o.Subscribers) {
		toSerialize["subscribers"] = o.Subscribers
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.ReporterEmail.IsSet() {
		toSerialize["reporterEmail"] = o.ReporterEmail.Get()
	}
	if o.PageUrl.IsSet() {
		toSerialize["pageUrl"] = o.PageUrl.Get()
	}
	if o.UserAgent.IsSet() {
		toSerialize["userAgent"] = o.UserAgent.Get()
	}
	if o.Viewport.IsSet() {
		toSerialize["viewport"] = o.Viewport.Get()
	}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if o.Notify.IsSet() {
		toSerialize["notify"] = o.Notify.Get()
	}
	return toSerialize, nil
}

func (o *CreatePublicBugRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePublicBugRequest := _CreatePublicBugRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePublicBugRequest)

	if err != nil {
		return err
	}

	*o = CreatePublicBugRequest(varCreatePublicBugRequest)

	return err
}

type NullableCreatePublicBugRequest struct {
	value *CreatePublicBugRequest
	isSet bool
}

func (v NullableCreatePublicBugRequest) Get() *CreatePublicBugRequest {
	return v.value
}

func (v *NullableCreatePublicBugRequest) Set(val *CreatePublicBugRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePublicBugRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePublicBugRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePublicBugRequest(val *CreatePublicBugRequest) *NullableCreatePublicBugRequest {
	return &NullableCreatePublicBugRequest{value: val, isSet: true}
}

func (v NullableCreatePublicBugRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePublicBugRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


