/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListGatesResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGatesResponseDataInner{}

// ListGatesResponseDataInner struct for ListGatesResponseDataInner
type ListGatesResponseDataInner struct {
	// Stable opaque gate id (`gat_…`).
	Id string `json:"id"`
	// Stable gate key used by SDKs (`Shipeasy.checkGate(user, '<name>')`). Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create — rename = delete + recreate.
	Name string `json:"name" validate:"regexp=^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$"`
	Enabled ListGatesResponseDataInnerEnabled `json:"enabled"`
	// Current rollout in basis points (0–10000).
	RolloutPct int32 `json:"rolloutPct"`
	Rules []ListGatesResponseDataInnerRulesInner `json:"rules,omitempty"`
	// Hash salt used for percentage bucketing.
	Salt *string `json:"salt,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Folder NullableString `json:"folder,omitempty"`
	// Group label (note: `groupName` in response, `group` in request).
	GroupName NullableString `json:"groupName,omitempty"`
	// Owner email (note: `ownerEmail` in response, `owner_email` in request).
	OwnerEmail NullableString `json:"ownerEmail,omitempty"`
	Stack []ListGatesResponseDataInnerStackInner `json:"stack,omitempty"`
	// ISO-8601 timestamp of last mutation.
	UpdatedAt string `json:"updatedAt"`
}

type _ListGatesResponseDataInner ListGatesResponseDataInner

// NewListGatesResponseDataInner instantiates a new ListGatesResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGatesResponseDataInner(id string, name string, enabled ListGatesResponseDataInnerEnabled, rolloutPct int32, updatedAt string) *ListGatesResponseDataInner {
	this := ListGatesResponseDataInner{}
	this.Id = id
	this.Name = name
	this.Enabled = enabled
	this.RolloutPct = rolloutPct
	this.UpdatedAt = updatedAt
	return &this
}

// NewListGatesResponseDataInnerWithDefaults instantiates a new ListGatesResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGatesResponseDataInnerWithDefaults() *ListGatesResponseDataInner {
	this := ListGatesResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListGatesResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListGatesResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListGatesResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListGatesResponseDataInner) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value
func (o *ListGatesResponseDataInner) GetEnabled() ListGatesResponseDataInnerEnabled {
	if o == nil {
		var ret ListGatesResponseDataInnerEnabled
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetEnabledOk() (*ListGatesResponseDataInnerEnabled, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ListGatesResponseDataInner) SetEnabled(v ListGatesResponseDataInnerEnabled) {
	o.Enabled = v
}

// GetRolloutPct returns the RolloutPct field value
func (o *ListGatesResponseDataInner) GetRolloutPct() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RolloutPct
}

// GetRolloutPctOk returns a tuple with the RolloutPct field value
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetRolloutPctOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolloutPct, true
}

// SetRolloutPct sets field value
func (o *ListGatesResponseDataInner) SetRolloutPct(v int32) {
	o.RolloutPct = v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *ListGatesResponseDataInner) GetRules() []ListGatesResponseDataInnerRulesInner {
	if o == nil || IsNil(o.Rules) {
		var ret []ListGatesResponseDataInnerRulesInner
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetRulesOk() ([]ListGatesResponseDataInnerRulesInner, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []ListGatesResponseDataInnerRulesInner and assigns it to the Rules field.
func (o *ListGatesResponseDataInner) SetRules(v []ListGatesResponseDataInnerRulesInner) {
	o.Rules = v
}

// GetSalt returns the Salt field value if set, zero value otherwise.
func (o *ListGatesResponseDataInner) GetSalt() string {
	if o == nil || IsNil(o.Salt) {
		var ret string
		return ret
	}
	return *o.Salt
}

// GetSaltOk returns a tuple with the Salt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetSaltOk() (*string, bool) {
	if o == nil || IsNil(o.Salt) {
		return nil, false
	}
	return o.Salt, true
}

// HasSalt returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasSalt() bool {
	if o != nil && !IsNil(o.Salt) {
		return true
	}

	return false
}

// SetSalt gets a reference to the given string and assigns it to the Salt field.
func (o *ListGatesResponseDataInner) SetSalt(v string) {
	o.Salt = &v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ListGatesResponseDataInner) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ListGatesResponseDataInner) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ListGatesResponseDataInner) UnsetTitle() {
	o.Title.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ListGatesResponseDataInner) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ListGatesResponseDataInner) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ListGatesResponseDataInner) UnsetDescription() {
	o.Description.Unset()
}

// GetFolder returns the Folder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetFolder() string {
	if o == nil || IsNil(o.Folder.Get()) {
		var ret string
		return ret
	}
	return *o.Folder.Get()
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Folder.Get(), o.Folder.IsSet()
}

// HasFolder returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasFolder() bool {
	if o != nil && o.Folder.IsSet() {
		return true
	}

	return false
}

// SetFolder gets a reference to the given NullableString and assigns it to the Folder field.
func (o *ListGatesResponseDataInner) SetFolder(v string) {
	o.Folder.Set(&v)
}
// SetFolderNil sets the value for Folder to be an explicit nil
func (o *ListGatesResponseDataInner) SetFolderNil() {
	o.Folder.Set(nil)
}

// UnsetFolder ensures that no value is present for Folder, not even an explicit nil
func (o *ListGatesResponseDataInner) UnsetFolder() {
	o.Folder.Unset()
}

// GetGroupName returns the GroupName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetGroupName() string {
	if o == nil || IsNil(o.GroupName.Get()) {
		var ret string
		return ret
	}
	return *o.GroupName.Get()
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupName.Get(), o.GroupName.IsSet()
}

// HasGroupName returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasGroupName() bool {
	if o != nil && o.GroupName.IsSet() {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given NullableString and assigns it to the GroupName field.
func (o *ListGatesResponseDataInner) SetGroupName(v string) {
	o.GroupName.Set(&v)
}
// SetGroupNameNil sets the value for GroupName to be an explicit nil
func (o *ListGatesResponseDataInner) SetGroupNameNil() {
	o.GroupName.Set(nil)
}

// UnsetGroupName ensures that no value is present for GroupName, not even an explicit nil
func (o *ListGatesResponseDataInner) UnsetGroupName() {
	o.GroupName.Unset()
}

// GetOwnerEmail returns the OwnerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetOwnerEmail() string {
	if o == nil || IsNil(o.OwnerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerEmail.Get()
}

// GetOwnerEmailOk returns a tuple with the OwnerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetOwnerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerEmail.Get(), o.OwnerEmail.IsSet()
}

// HasOwnerEmail returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasOwnerEmail() bool {
	if o != nil && o.OwnerEmail.IsSet() {
		return true
	}

	return false
}

// SetOwnerEmail gets a reference to the given NullableString and assigns it to the OwnerEmail field.
func (o *ListGatesResponseDataInner) SetOwnerEmail(v string) {
	o.OwnerEmail.Set(&v)
}
// SetOwnerEmailNil sets the value for OwnerEmail to be an explicit nil
func (o *ListGatesResponseDataInner) SetOwnerEmailNil() {
	o.OwnerEmail.Set(nil)
}

// UnsetOwnerEmail ensures that no value is present for OwnerEmail, not even an explicit nil
func (o *ListGatesResponseDataInner) UnsetOwnerEmail() {
	o.OwnerEmail.Unset()
}

// GetStack returns the Stack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGatesResponseDataInner) GetStack() []ListGatesResponseDataInnerStackInner {
	if o == nil {
		var ret []ListGatesResponseDataInnerStackInner
		return ret
	}
	return o.Stack
}

// GetStackOk returns a tuple with the Stack field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGatesResponseDataInner) GetStackOk() ([]ListGatesResponseDataInnerStackInner, bool) {
	if o == nil || IsNil(o.Stack) {
		return nil, false
	}
	return o.Stack, true
}

// HasStack returns a boolean if a field has been set.
func (o *ListGatesResponseDataInner) HasStack() bool {
	if o != nil && !IsNil(o.Stack) {
		return true
	}

	return false
}

// SetStack gets a reference to the given []ListGatesResponseDataInnerStackInner and assigns it to the Stack field.
func (o *ListGatesResponseDataInner) SetStack(v []ListGatesResponseDataInnerStackInner) {
	o.Stack = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListGatesResponseDataInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListGatesResponseDataInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListGatesResponseDataInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o ListGatesResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGatesResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["enabled"] = o.Enabled
	toSerialize["rolloutPct"] = o.RolloutPct
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.Salt) {
		toSerialize["salt"] = o.Salt
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Folder.IsSet() {
		toSerialize["folder"] = o.Folder.Get()
	}
	if o.GroupName.IsSet() {
		toSerialize["groupName"] = o.GroupName.Get()
	}
	if o.OwnerEmail.IsSet() {
		toSerialize["ownerEmail"] = o.OwnerEmail.Get()
	}
	if o.Stack != nil {
		toSerialize["stack"] = o.Stack
	}
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ListGatesResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"enabled",
		"rolloutPct",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListGatesResponseDataInner := _ListGatesResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListGatesResponseDataInner)

	if err != nil {
		return err
	}

	*o = ListGatesResponseDataInner(varListGatesResponseDataInner)

	return err
}

type NullableListGatesResponseDataInner struct {
	value *ListGatesResponseDataInner
	isSet bool
}

func (v NullableListGatesResponseDataInner) Get() *ListGatesResponseDataInner {
	return v.value
}

func (v *NullableListGatesResponseDataInner) Set(val *ListGatesResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListGatesResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListGatesResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGatesResponseDataInner(val *ListGatesResponseDataInner) *NullableListGatesResponseDataInner {
	return &NullableListGatesResponseDataInner{value: val, isSet: true}
}

func (v NullableListGatesResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGatesResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


