/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListEventsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEventsResponseInner{}

// ListEventsResponseInner A catalogued event.
type ListEventsResponseInner struct {
	// Stable opaque event id.
	Id string `json:"id"`
	// Event name — the handle metric queries reference.
	Name string `json:"name"`
	// Optional folder name used to group items in the dashboard. Part of the SDK lookup key: an item in folder `checkout` named `new-cart` is referenced as `checkout/new-cart` from the SDK.
	Folder NullableString `json:"folder,omitempty" validate:"regexp=^[a-zA-Z0-9_-]+$"`
	// Human-readable description, or `null` if none set.
	Description NullableString `json:"description"`
	// Typed properties declared on the event.
	Properties []ListEventsResponseInnerPropertiesInner `json:"properties"`
	// `1` if this is an auto-discovered name awaiting approval (metrics on it fail until approved), `0` if approved/usable.
	Pending int32 `json:"pending"`
	// ISO-8601 timestamp of creation.
	CreatedAt string `json:"createdAt"`
}

type _ListEventsResponseInner ListEventsResponseInner

// NewListEventsResponseInner instantiates a new ListEventsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEventsResponseInner(id string, name string, description NullableString, properties []ListEventsResponseInnerPropertiesInner, pending int32, createdAt string) *ListEventsResponseInner {
	this := ListEventsResponseInner{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Properties = properties
	this.Pending = pending
	this.CreatedAt = createdAt
	return &this
}

// NewListEventsResponseInnerWithDefaults instantiates a new ListEventsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEventsResponseInnerWithDefaults() *ListEventsResponseInner {
	this := ListEventsResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListEventsResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListEventsResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListEventsResponseInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListEventsResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListEventsResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListEventsResponseInner) SetName(v string) {
	o.Name = v
}

// GetFolder returns the Folder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListEventsResponseInner) GetFolder() string {
	if o == nil || IsNil(o.Folder.Get()) {
		var ret string
		return ret
	}
	return *o.Folder.Get()
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListEventsResponseInner) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Folder.Get(), o.Folder.IsSet()
}

// HasFolder returns a boolean if a field has been set.
func (o *ListEventsResponseInner) HasFolder() bool {
	if o != nil && o.Folder.IsSet() {
		return true
	}

	return false
}

// SetFolder gets a reference to the given NullableString and assigns it to the Folder field.
func (o *ListEventsResponseInner) SetFolder(v string) {
	o.Folder.Set(&v)
}
// SetFolderNil sets the value for Folder to be an explicit nil
func (o *ListEventsResponseInner) SetFolderNil() {
	o.Folder.Set(nil)
}

// UnsetFolder ensures that no value is present for Folder, not even an explicit nil
func (o *ListEventsResponseInner) UnsetFolder() {
	o.Folder.Unset()
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListEventsResponseInner) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListEventsResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *ListEventsResponseInner) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetProperties returns the Properties field value
func (o *ListEventsResponseInner) GetProperties() []ListEventsResponseInnerPropertiesInner {
	if o == nil {
		var ret []ListEventsResponseInnerPropertiesInner
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *ListEventsResponseInner) GetPropertiesOk() ([]ListEventsResponseInnerPropertiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *ListEventsResponseInner) SetProperties(v []ListEventsResponseInnerPropertiesInner) {
	o.Properties = v
}

// GetPending returns the Pending field value
func (o *ListEventsResponseInner) GetPending() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *ListEventsResponseInner) GetPendingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pending, true
}

// SetPending sets field value
func (o *ListEventsResponseInner) SetPending(v int32) {
	o.Pending = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListEventsResponseInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListEventsResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListEventsResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o ListEventsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEventsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.Folder.IsSet() {
		toSerialize["folder"] = o.Folder.Get()
	}
	toSerialize["description"] = o.Description.Get()
	toSerialize["properties"] = o.Properties
	toSerialize["pending"] = o.Pending
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ListEventsResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"properties",
		"pending",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEventsResponseInner := _ListEventsResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListEventsResponseInner)

	if err != nil {
		return err
	}

	*o = ListEventsResponseInner(varListEventsResponseInner)

	return err
}

type NullableListEventsResponseInner struct {
	value *ListEventsResponseInner
	isSet bool
}

func (v NullableListEventsResponseInner) Get() *ListEventsResponseInner {
	return v.value
}

func (v *NullableListEventsResponseInner) Set(val *ListEventsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListEventsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListEventsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEventsResponseInner(val *ListEventsResponseInner) *NullableListEventsResponseInner {
	return &NullableListEventsResponseInner{value: val, isSet: true}
}

func (v NullableListEventsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEventsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


