/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListConfigActivityResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListConfigActivityResponseInner{}

// ListConfigActivityResponseInner struct for ListConfigActivityResponseInner
type ListConfigActivityResponseInner struct {
	// Optional gate name. Only callers that pass the gate are enrolled in the experiment.
	Id NullableString `json:"id"`
	// Audit action (e.g. `config.create`, `config.publish`).
	Action string `json:"action"`
	// Optional gate name. Only callers that pass the gate are enrolled in the experiment.
	ActorEmail NullableString `json:"actorEmail"`
	ActorType string `json:"actorType"`
	Payload interface{} `json:"payload"`
	// ISO-8601 timestamp.
	CreatedAt string `json:"createdAt"`
}

type _ListConfigActivityResponseInner ListConfigActivityResponseInner

// NewListConfigActivityResponseInner instantiates a new ListConfigActivityResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConfigActivityResponseInner(id NullableString, action string, actorEmail NullableString, actorType string, payload interface{}, createdAt string) *ListConfigActivityResponseInner {
	this := ListConfigActivityResponseInner{}
	this.Id = id
	this.Action = action
	this.ActorEmail = actorEmail
	this.ActorType = actorType
	this.Payload = payload
	this.CreatedAt = createdAt
	return &this
}

// NewListConfigActivityResponseInnerWithDefaults instantiates a new ListConfigActivityResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConfigActivityResponseInnerWithDefaults() *ListConfigActivityResponseInner {
	this := ListConfigActivityResponseInner{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListConfigActivityResponseInner) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListConfigActivityResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ListConfigActivityResponseInner) SetId(v string) {
	o.Id.Set(&v)
}

// GetAction returns the Action field value
func (o *ListConfigActivityResponseInner) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ListConfigActivityResponseInner) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ListConfigActivityResponseInner) SetAction(v string) {
	o.Action = v
}

// GetActorEmail returns the ActorEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListConfigActivityResponseInner) GetActorEmail() string {
	if o == nil || o.ActorEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.ActorEmail.Get()
}

// GetActorEmailOk returns a tuple with the ActorEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListConfigActivityResponseInner) GetActorEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActorEmail.Get(), o.ActorEmail.IsSet()
}

// SetActorEmail sets field value
func (o *ListConfigActivityResponseInner) SetActorEmail(v string) {
	o.ActorEmail.Set(&v)
}

// GetActorType returns the ActorType field value
func (o *ListConfigActivityResponseInner) GetActorType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActorType
}

// GetActorTypeOk returns a tuple with the ActorType field value
// and a boolean to check if the value has been set.
func (o *ListConfigActivityResponseInner) GetActorTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActorType, true
}

// SetActorType sets field value
func (o *ListConfigActivityResponseInner) SetActorType(v string) {
	o.ActorType = v
}

// GetPayload returns the Payload field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ListConfigActivityResponseInner) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListConfigActivityResponseInner) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *ListConfigActivityResponseInner) SetPayload(v interface{}) {
	o.Payload = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListConfigActivityResponseInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListConfigActivityResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListConfigActivityResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o ListConfigActivityResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListConfigActivityResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["action"] = o.Action
	toSerialize["actorEmail"] = o.ActorEmail.Get()
	toSerialize["actorType"] = o.ActorType
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ListConfigActivityResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"action",
		"actorEmail",
		"actorType",
		"payload",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListConfigActivityResponseInner := _ListConfigActivityResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListConfigActivityResponseInner)

	if err != nil {
		return err
	}

	*o = ListConfigActivityResponseInner(varListConfigActivityResponseInner)

	return err
}

type NullableListConfigActivityResponseInner struct {
	value *ListConfigActivityResponseInner
	isSet bool
}

func (v NullableListConfigActivityResponseInner) Get() *ListConfigActivityResponseInner {
	return v.value
}

func (v *NullableListConfigActivityResponseInner) Set(val *ListConfigActivityResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListConfigActivityResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListConfigActivityResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConfigActivityResponseInner(val *ListConfigActivityResponseInner) *NullableListConfigActivityResponseInner {
	return &NullableListConfigActivityResponseInner{value: val, isSet: true}
}

func (v NullableListConfigActivityResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConfigActivityResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


