/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PushI18nKeysResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushI18nKeysResponse{}

// PushI18nKeysResponse Result of an insert-only key push.
type PushI18nKeysResponse struct {
	// Key names that were newly inserted.
	Added []string `json:"added"`
	// Key names that already existed and were left untouched.
	Skipped []string `json:"skipped"`
	// Number of keys inserted (== `added.length`).
	PushedCount float32 `json:"pushed_count"`
	// Number of keys skipped (== `skipped.length`).
	SkippedCount float32 `json:"skipped_count"`
	// The chunk the keys were filed under.
	Chunk *string `json:"chunk,omitempty"`
}

type _PushI18nKeysResponse PushI18nKeysResponse

// NewPushI18nKeysResponse instantiates a new PushI18nKeysResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushI18nKeysResponse(added []string, skipped []string, pushedCount float32, skippedCount float32) *PushI18nKeysResponse {
	this := PushI18nKeysResponse{}
	this.Added = added
	this.Skipped = skipped
	this.PushedCount = pushedCount
	this.SkippedCount = skippedCount
	return &this
}

// NewPushI18nKeysResponseWithDefaults instantiates a new PushI18nKeysResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushI18nKeysResponseWithDefaults() *PushI18nKeysResponse {
	this := PushI18nKeysResponse{}
	return &this
}

// GetAdded returns the Added field value
func (o *PushI18nKeysResponse) GetAdded() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Added
}

// GetAddedOk returns a tuple with the Added field value
// and a boolean to check if the value has been set.
func (o *PushI18nKeysResponse) GetAddedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Added, true
}

// SetAdded sets field value
func (o *PushI18nKeysResponse) SetAdded(v []string) {
	o.Added = v
}

// GetSkipped returns the Skipped field value
func (o *PushI18nKeysResponse) GetSkipped() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value
// and a boolean to check if the value has been set.
func (o *PushI18nKeysResponse) GetSkippedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Skipped, true
}

// SetSkipped sets field value
func (o *PushI18nKeysResponse) SetSkipped(v []string) {
	o.Skipped = v
}

// GetPushedCount returns the PushedCount field value
func (o *PushI18nKeysResponse) GetPushedCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PushedCount
}

// GetPushedCountOk returns a tuple with the PushedCount field value
// and a boolean to check if the value has been set.
func (o *PushI18nKeysResponse) GetPushedCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PushedCount, true
}

// SetPushedCount sets field value
func (o *PushI18nKeysResponse) SetPushedCount(v float32) {
	o.PushedCount = v
}

// GetSkippedCount returns the SkippedCount field value
func (o *PushI18nKeysResponse) GetSkippedCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SkippedCount
}

// GetSkippedCountOk returns a tuple with the SkippedCount field value
// and a boolean to check if the value has been set.
func (o *PushI18nKeysResponse) GetSkippedCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkippedCount, true
}

// SetSkippedCount sets field value
func (o *PushI18nKeysResponse) SetSkippedCount(v float32) {
	o.SkippedCount = v
}

// GetChunk returns the Chunk field value if set, zero value otherwise.
func (o *PushI18nKeysResponse) GetChunk() string {
	if o == nil || IsNil(o.Chunk) {
		var ret string
		return ret
	}
	return *o.Chunk
}

// GetChunkOk returns a tuple with the Chunk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushI18nKeysResponse) GetChunkOk() (*string, bool) {
	if o == nil || IsNil(o.Chunk) {
		return nil, false
	}
	return o.Chunk, true
}

// HasChunk returns a boolean if a field has been set.
func (o *PushI18nKeysResponse) HasChunk() bool {
	if o != nil && !IsNil(o.Chunk) {
		return true
	}

	return false
}

// SetChunk gets a reference to the given string and assigns it to the Chunk field.
func (o *PushI18nKeysResponse) SetChunk(v string) {
	o.Chunk = &v
}

func (o PushI18nKeysResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushI18nKeysResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["added"] = o.Added
	toSerialize["skipped"] = o.Skipped
	toSerialize["pushed_count"] = o.PushedCount
	toSerialize["skipped_count"] = o.SkippedCount
	if !IsNil(o.Chunk) {
		toSerialize["chunk"] = o.Chunk
	}
	return toSerialize, nil
}

func (o *PushI18nKeysResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"added",
		"skipped",
		"pushed_count",
		"skipped_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPushI18nKeysResponse := _PushI18nKeysResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPushI18nKeysResponse)

	if err != nil {
		return err
	}

	*o = PushI18nKeysResponse(varPushI18nKeysResponse)

	return err
}

type NullablePushI18nKeysResponse struct {
	value *PushI18nKeysResponse
	isSet bool
}

func (v NullablePushI18nKeysResponse) Get() *PushI18nKeysResponse {
	return v.value
}

func (v *NullablePushI18nKeysResponse) Set(val *PushI18nKeysResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePushI18nKeysResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePushI18nKeysResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushI18nKeysResponse(val *PushI18nKeysResponse) *NullablePushI18nKeysResponse {
	return &NullablePushI18nKeysResponse{value: val, isSet: true}
}

func (v NullablePushI18nKeysResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushI18nKeysResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


