/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the ErrorSeriesResponseRowsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorSeriesResponseRowsInner{}

// ErrorSeriesResponseRowsInner struct for ErrorSeriesResponseRowsInner
type ErrorSeriesResponseRowsInner struct {
	// Bucket start, epoch seconds, floor-aligned to `bucket`.
	T int32 `json:"t"`
	// Occurrence count in the bucket (sample-interval weighted).
	V float32 `json:"v"`
	AdditionalProperties map[string]interface{}
}

type _ErrorSeriesResponseRowsInner ErrorSeriesResponseRowsInner

// NewErrorSeriesResponseRowsInner instantiates a new ErrorSeriesResponseRowsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorSeriesResponseRowsInner(t int32, v float32) *ErrorSeriesResponseRowsInner {
	this := ErrorSeriesResponseRowsInner{}
	this.T = t
	this.V = v
	return &this
}

// NewErrorSeriesResponseRowsInnerWithDefaults instantiates a new ErrorSeriesResponseRowsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorSeriesResponseRowsInnerWithDefaults() *ErrorSeriesResponseRowsInner {
	this := ErrorSeriesResponseRowsInner{}
	return &this
}

// GetT returns the T field value
func (o *ErrorSeriesResponseRowsInner) GetT() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *ErrorSeriesResponseRowsInner) GetTOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *ErrorSeriesResponseRowsInner) SetT(v int32) {
	o.T = v
}

// GetV returns the V field value
func (o *ErrorSeriesResponseRowsInner) GetV() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.V
}

// GetVOk returns a tuple with the V field value
// and a boolean to check if the value has been set.
func (o *ErrorSeriesResponseRowsInner) GetVOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.V, true
}

// SetV sets field value
func (o *ErrorSeriesResponseRowsInner) SetV(v float32) {
	o.V = v
}

func (o ErrorSeriesResponseRowsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorSeriesResponseRowsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["t"] = o.T
	toSerialize["v"] = o.V

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ErrorSeriesResponseRowsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"t",
		"v",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorSeriesResponseRowsInner := _ErrorSeriesResponseRowsInner{}

	err = json.Unmarshal(data, &varErrorSeriesResponseRowsInner)

	if err != nil {
		return err
	}

	*o = ErrorSeriesResponseRowsInner(varErrorSeriesResponseRowsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "t")
		delete(additionalProperties, "v")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableErrorSeriesResponseRowsInner struct {
	value *ErrorSeriesResponseRowsInner
	isSet bool
}

func (v NullableErrorSeriesResponseRowsInner) Get() *ErrorSeriesResponseRowsInner {
	return v.value
}

func (v *NullableErrorSeriesResponseRowsInner) Set(val *ErrorSeriesResponseRowsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorSeriesResponseRowsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorSeriesResponseRowsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorSeriesResponseRowsInner(val *ErrorSeriesResponseRowsInner) *NullableErrorSeriesResponseRowsInner {
	return &NullableErrorSeriesResponseRowsInner{value: val, isSet: true}
}

func (v NullableErrorSeriesResponseRowsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorSeriesResponseRowsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


