/*
Shipeasy Admin API (server-SDK surface)

The slice of the Shipeasy admin API that the published server SDKs expose as their optional `AdminClient`. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Three capabilities, nothing else:  - **File a public ticket** — a bug or a feature request onto the project's ops queue. - **Toggle a kill switch** — flip the switch itself, or one of its named sub-switches, on one environment. - **Manage a flag's whitelist** — read, replace, add to, or remove from the allowlist that admits specific identities ahead of every targeting rule.  Everything else in the admin API is reachable through the Shipeasy CLI and MCP server, which speak the complete contract (`openapi.yaml`).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// OpsItemPriority Triage priority of a queue item. The lowest tier is `nice_to_have` (not `low`) — carried over from the feature-request \"importance\" scale this priority set replaced.
type OpsItemPriority string

// List of OpsItemPriority
const (
	OPSITEMPRIORITY_NICE_TO_HAVE OpsItemPriority = "nice_to_have"
	OPSITEMPRIORITY_MEDIUM OpsItemPriority = "medium"
	OPSITEMPRIORITY_HIGH OpsItemPriority = "high"
	OPSITEMPRIORITY_CRITICAL OpsItemPriority = "critical"
)

// All allowed values of OpsItemPriority enum
var AllowedOpsItemPriorityEnumValues = []OpsItemPriority{
	"nice_to_have",
	"medium",
	"high",
	"critical",
}

func (v *OpsItemPriority) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OpsItemPriority(value)
	for _, existing := range AllowedOpsItemPriorityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OpsItemPriority", value)
}

// NewOpsItemPriorityFromValue returns a pointer to a valid OpsItemPriority
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOpsItemPriorityFromValue(v string) (*OpsItemPriority, error) {
	ev := OpsItemPriority(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OpsItemPriority: valid values are %v", v, AllowedOpsItemPriorityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OpsItemPriority) IsValid() bool {
	for _, existing := range AllowedOpsItemPriorityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OpsItemPriority value
func (v OpsItemPriority) Ptr() *OpsItemPriority {
	return &v
}

type NullableOpsItemPriority struct {
	value *OpsItemPriority
	isSet bool
}

func (v NullableOpsItemPriority) Get() *OpsItemPriority {
	return v.value
}

func (v *NullableOpsItemPriority) Set(val *OpsItemPriority) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsItemPriority) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsItemPriority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsItemPriority(val *OpsItemPriority) *NullableOpsItemPriority {
	return &NullableOpsItemPriority{value: val, isSet: true}
}

func (v NullableOpsItemPriority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsItemPriority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

