/*
Shipeasy Admin API (SDK admin subset)

Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GateApiRowRulesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GateApiRowRulesInner{}

// GateApiRowRulesInner Single targeting predicate. A gate's `rules` array is evaluated with AND semantics; use the gatekeeper `stack` for OR / fall-through logic.
type GateApiRowRulesInner struct {
	// Attribute key on the evaluation context (e.g. `country`, `plan`, `email`). Matched case-sensitively against `Shipeasy.checkGate(user, name)` input.
	Attr string `json:"attr"`
	// Comparison operator. Equality: `eq`/`neq`. Set membership: `in`/`not_in` (value is an array). Numeric order: `gt`/`gte`/`lt`/`lte`. Semver order: `semver_gt`/`semver_gte`/`semver_lt`/`semver_lte` (value is a dotted version like `4.2.0`). String: `contains` (substring), `regex` (JS-flavour pattern, value is the pattern string). Cross-resource references (evaluated only on the worker hot path, where both KV blobs load): `gate_pass` (`value` is another gate's name — true when that gate passes for the same caller); `exp_in` (`attr` is a running experiment's name, `value` is a group name, `\"$holdout\"`, or `\"$any\"` — true when the caller is in that variant / the universe holdout / any variant).
	Op string `json:"op"`
	Value interface{} `json:"value"`
}

type _GateApiRowRulesInner GateApiRowRulesInner

// NewGateApiRowRulesInner instantiates a new GateApiRowRulesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGateApiRowRulesInner(attr string, op string, value interface{}) *GateApiRowRulesInner {
	this := GateApiRowRulesInner{}
	this.Attr = attr
	this.Op = op
	this.Value = value
	return &this
}

// NewGateApiRowRulesInnerWithDefaults instantiates a new GateApiRowRulesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGateApiRowRulesInnerWithDefaults() *GateApiRowRulesInner {
	this := GateApiRowRulesInner{}
	return &this
}

// GetAttr returns the Attr field value
func (o *GateApiRowRulesInner) GetAttr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attr
}

// GetAttrOk returns a tuple with the Attr field value
// and a boolean to check if the value has been set.
func (o *GateApiRowRulesInner) GetAttrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attr, true
}

// SetAttr sets field value
func (o *GateApiRowRulesInner) SetAttr(v string) {
	o.Attr = v
}

// GetOp returns the Op field value
func (o *GateApiRowRulesInner) GetOp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *GateApiRowRulesInner) GetOpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *GateApiRowRulesInner) SetOp(v string) {
	o.Op = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GateApiRowRulesInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GateApiRowRulesInner) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *GateApiRowRulesInner) SetValue(v interface{}) {
	o.Value = v
}

func (o GateApiRowRulesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GateApiRowRulesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attr"] = o.Attr
	toSerialize["op"] = o.Op
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *GateApiRowRulesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attr",
		"op",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGateApiRowRulesInner := _GateApiRowRulesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGateApiRowRulesInner)

	if err != nil {
		return err
	}

	*o = GateApiRowRulesInner(varGateApiRowRulesInner)

	return err
}

type NullableGateApiRowRulesInner struct {
	value *GateApiRowRulesInner
	isSet bool
}

func (v NullableGateApiRowRulesInner) Get() *GateApiRowRulesInner {
	return v.value
}

func (v *NullableGateApiRowRulesInner) Set(val *GateApiRowRulesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGateApiRowRulesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGateApiRowRulesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGateApiRowRulesInner(val *GateApiRowRulesInner) *NullableGateApiRowRulesInner {
	return &NullableGateApiRowRulesInner{value: val, isSet: true}
}

func (v NullableGateApiRowRulesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGateApiRowRulesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


