/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the ListMetricsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetricsResponseInner{}

// ListMetricsResponseInner A metric definition.
type ListMetricsResponseInner struct {
	// Stable opaque metric id.
	Id string `json:"id"`
	// Metric key.
	Name string `json:"name"`
	// Folder grouping the metric, or `null`.
	Folder NullableString `json:"folder"`
	// Source event name (camelCase in response).
	EventName string `json:"eventName"`
	// Rendered DSL text form of the query, or `null` if it could not be rendered.
	Query NullableString `json:"query"`
	// Typed query IR, or `null` for a metric whose IR was never populated (re-save it to backfill).
	QueryIr NullableQueryIr `json:"queryIr"`
	// Human-friendly display name shown in the dashboard, or `null` to fall back to `name`.
	DisplayName NullableString `json:"displayName"`
	// Id of the metric preset this metric was created from, or `null` for a custom metric.
	PresetId NullableString `json:"presetId"`
	// Display unit (e.g. `ms`, `%`, `$`), or `null` when unitless.
	Unit NullableString `json:"unit"`
	// Monotonic save counter — incremented on every update.
	Version int32 `json:"version"`
	// ISO-8601 soft-delete (archive) timestamp, or `null` while the metric is live.
	DeletedAt NullableString `json:"deletedAt"`
	// Email of the user who created the metric, or `null` when unknown. List responses only.
	CreatorEmail NullableString `json:"creatorEmail,omitempty"`
	// Email of the user who last edited the metric, or `null` when unknown. List responses only.
	UpdaterEmail NullableString `json:"updaterEmail,omitempty"`
	// Desired direction of movement. `higher_better` (default), `lower_better`, or `neutral` (guardrail).
	Direction *string `json:"direction,omitempty"`
	// Winsorise percentile applied to the metric.
	WinsorizePct *float32 `json:"winsorizePct,omitempty"`
	// Metric-level default minimum effect of interest (relative, 0–1), or `null`.
	DefaultMinEffectOfInterest NullableFloat32 `json:"defaultMinEffectOfInterest,omitempty"`
	// ISO-8601 creation timestamp, or `null` on legacy rows created before the column existed.
	CreatedAt NullableString `json:"createdAt,omitempty"`
	// ISO-8601 last-update timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListMetricsResponseInner ListMetricsResponseInner

// NewListMetricsResponseInner instantiates a new ListMetricsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetricsResponseInner(id string, name string, folder NullableString, eventName string, query NullableString, queryIr NullableQueryIr, displayName NullableString, presetId NullableString, unit NullableString, version int32, deletedAt NullableString) *ListMetricsResponseInner {
	this := ListMetricsResponseInner{}
	this.Id = id
	this.Name = name
	this.Folder = folder
	this.EventName = eventName
	this.Query = query
	this.QueryIr = queryIr
	this.DisplayName = displayName
	this.PresetId = presetId
	this.Unit = unit
	this.Version = version
	this.DeletedAt = deletedAt
	return &this
}

// NewListMetricsResponseInnerWithDefaults instantiates a new ListMetricsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetricsResponseInnerWithDefaults() *ListMetricsResponseInner {
	this := ListMetricsResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListMetricsResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListMetricsResponseInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListMetricsResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListMetricsResponseInner) SetName(v string) {
	o.Name = v
}

// GetFolder returns the Folder field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetFolder() string {
	if o == nil || o.Folder.Get() == nil {
		var ret string
		return ret
	}

	return *o.Folder.Get()
}

// GetFolderOk returns a tuple with the Folder field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Folder.Get(), o.Folder.IsSet()
}

// SetFolder sets field value
func (o *ListMetricsResponseInner) SetFolder(v string) {
	o.Folder.Set(&v)
}

// GetEventName returns the EventName field value
func (o *ListMetricsResponseInner) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *ListMetricsResponseInner) SetEventName(v string) {
	o.EventName = v
}

// GetQuery returns the Query field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetQuery() string {
	if o == nil || o.Query.Get() == nil {
		var ret string
		return ret
	}

	return *o.Query.Get()
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Query.Get(), o.Query.IsSet()
}

// SetQuery sets field value
func (o *ListMetricsResponseInner) SetQuery(v string) {
	o.Query.Set(&v)
}

// GetQueryIr returns the QueryIr field value
// If the value is explicit nil, the zero value for QueryIr will be returned
func (o *ListMetricsResponseInner) GetQueryIr() QueryIr {
	if o == nil || o.QueryIr.Get() == nil {
		var ret QueryIr
		return ret
	}

	return *o.QueryIr.Get()
}

// GetQueryIrOk returns a tuple with the QueryIr field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetQueryIrOk() (*QueryIr, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryIr.Get(), o.QueryIr.IsSet()
}

// SetQueryIr sets field value
func (o *ListMetricsResponseInner) SetQueryIr(v QueryIr) {
	o.QueryIr.Set(&v)
}

// GetDisplayName returns the DisplayName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetDisplayName() string {
	if o == nil || o.DisplayName.Get() == nil {
		var ret string
		return ret
	}

	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// SetDisplayName sets field value
func (o *ListMetricsResponseInner) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// GetPresetId returns the PresetId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetPresetId() string {
	if o == nil || o.PresetId.Get() == nil {
		var ret string
		return ret
	}

	return *o.PresetId.Get()
}

// GetPresetIdOk returns a tuple with the PresetId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetPresetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PresetId.Get(), o.PresetId.IsSet()
}

// SetPresetId sets field value
func (o *ListMetricsResponseInner) SetPresetId(v string) {
	o.PresetId.Set(&v)
}

// GetUnit returns the Unit field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetUnit() string {
	if o == nil || o.Unit.Get() == nil {
		var ret string
		return ret
	}

	return *o.Unit.Get()
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unit.Get(), o.Unit.IsSet()
}

// SetUnit sets field value
func (o *ListMetricsResponseInner) SetUnit(v string) {
	o.Unit.Set(&v)
}

// GetVersion returns the Version field value
func (o *ListMetricsResponseInner) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ListMetricsResponseInner) SetVersion(v int32) {
	o.Version = v
}

// GetDeletedAt returns the DeletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMetricsResponseInner) GetDeletedAt() string {
	if o == nil || o.DeletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// SetDeletedAt sets field value
func (o *ListMetricsResponseInner) SetDeletedAt(v string) {
	o.DeletedAt.Set(&v)
}

// GetCreatorEmail returns the CreatorEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListMetricsResponseInner) GetCreatorEmail() string {
	if o == nil || IsNil(o.CreatorEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CreatorEmail.Get()
}

// GetCreatorEmailOk returns a tuple with the CreatorEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetCreatorEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatorEmail.Get(), o.CreatorEmail.IsSet()
}

// HasCreatorEmail returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasCreatorEmail() bool {
	if o != nil && o.CreatorEmail.IsSet() {
		return true
	}

	return false
}

// SetCreatorEmail gets a reference to the given NullableString and assigns it to the CreatorEmail field.
func (o *ListMetricsResponseInner) SetCreatorEmail(v string) {
	o.CreatorEmail.Set(&v)
}
// SetCreatorEmailNil sets the value for CreatorEmail to be an explicit nil
func (o *ListMetricsResponseInner) SetCreatorEmailNil() {
	o.CreatorEmail.Set(nil)
}

// UnsetCreatorEmail ensures that no value is present for CreatorEmail, not even an explicit nil
func (o *ListMetricsResponseInner) UnsetCreatorEmail() {
	o.CreatorEmail.Unset()
}

// GetUpdaterEmail returns the UpdaterEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListMetricsResponseInner) GetUpdaterEmail() string {
	if o == nil || IsNil(o.UpdaterEmail.Get()) {
		var ret string
		return ret
	}
	return *o.UpdaterEmail.Get()
}

// GetUpdaterEmailOk returns a tuple with the UpdaterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetUpdaterEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdaterEmail.Get(), o.UpdaterEmail.IsSet()
}

// HasUpdaterEmail returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasUpdaterEmail() bool {
	if o != nil && o.UpdaterEmail.IsSet() {
		return true
	}

	return false
}

// SetUpdaterEmail gets a reference to the given NullableString and assigns it to the UpdaterEmail field.
func (o *ListMetricsResponseInner) SetUpdaterEmail(v string) {
	o.UpdaterEmail.Set(&v)
}
// SetUpdaterEmailNil sets the value for UpdaterEmail to be an explicit nil
func (o *ListMetricsResponseInner) SetUpdaterEmailNil() {
	o.UpdaterEmail.Set(nil)
}

// UnsetUpdaterEmail ensures that no value is present for UpdaterEmail, not even an explicit nil
func (o *ListMetricsResponseInner) UnsetUpdaterEmail() {
	o.UpdaterEmail.Unset()
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *ListMetricsResponseInner) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *ListMetricsResponseInner) SetDirection(v string) {
	o.Direction = &v
}

// GetWinsorizePct returns the WinsorizePct field value if set, zero value otherwise.
func (o *ListMetricsResponseInner) GetWinsorizePct() float32 {
	if o == nil || IsNil(o.WinsorizePct) {
		var ret float32
		return ret
	}
	return *o.WinsorizePct
}

// GetWinsorizePctOk returns a tuple with the WinsorizePct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetWinsorizePctOk() (*float32, bool) {
	if o == nil || IsNil(o.WinsorizePct) {
		return nil, false
	}
	return o.WinsorizePct, true
}

// HasWinsorizePct returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasWinsorizePct() bool {
	if o != nil && !IsNil(o.WinsorizePct) {
		return true
	}

	return false
}

// SetWinsorizePct gets a reference to the given float32 and assigns it to the WinsorizePct field.
func (o *ListMetricsResponseInner) SetWinsorizePct(v float32) {
	o.WinsorizePct = &v
}

// GetDefaultMinEffectOfInterest returns the DefaultMinEffectOfInterest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListMetricsResponseInner) GetDefaultMinEffectOfInterest() float32 {
	if o == nil || IsNil(o.DefaultMinEffectOfInterest.Get()) {
		var ret float32
		return ret
	}
	return *o.DefaultMinEffectOfInterest.Get()
}

// GetDefaultMinEffectOfInterestOk returns a tuple with the DefaultMinEffectOfInterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetDefaultMinEffectOfInterestOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultMinEffectOfInterest.Get(), o.DefaultMinEffectOfInterest.IsSet()
}

// HasDefaultMinEffectOfInterest returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasDefaultMinEffectOfInterest() bool {
	if o != nil && o.DefaultMinEffectOfInterest.IsSet() {
		return true
	}

	return false
}

// SetDefaultMinEffectOfInterest gets a reference to the given NullableFloat32 and assigns it to the DefaultMinEffectOfInterest field.
func (o *ListMetricsResponseInner) SetDefaultMinEffectOfInterest(v float32) {
	o.DefaultMinEffectOfInterest.Set(&v)
}
// SetDefaultMinEffectOfInterestNil sets the value for DefaultMinEffectOfInterest to be an explicit nil
func (o *ListMetricsResponseInner) SetDefaultMinEffectOfInterestNil() {
	o.DefaultMinEffectOfInterest.Set(nil)
}

// UnsetDefaultMinEffectOfInterest ensures that no value is present for DefaultMinEffectOfInterest, not even an explicit nil
func (o *ListMetricsResponseInner) UnsetDefaultMinEffectOfInterest() {
	o.DefaultMinEffectOfInterest.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListMetricsResponseInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMetricsResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *ListMetricsResponseInner) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ListMetricsResponseInner) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ListMetricsResponseInner) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ListMetricsResponseInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ListMetricsResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ListMetricsResponseInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ListMetricsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetricsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["folder"] = o.Folder.Get()
	toSerialize["eventName"] = o.EventName
	toSerialize["query"] = o.Query.Get()
	toSerialize["queryIr"] = o.QueryIr.Get()
	toSerialize["displayName"] = o.DisplayName.Get()
	toSerialize["presetId"] = o.PresetId.Get()
	toSerialize["unit"] = o.Unit.Get()
	toSerialize["version"] = o.Version
	toSerialize["deletedAt"] = o.DeletedAt.Get()
	if o.CreatorEmail.IsSet() {
		toSerialize["creatorEmail"] = o.CreatorEmail.Get()
	}
	if o.UpdaterEmail.IsSet() {
		toSerialize["updaterEmail"] = o.UpdaterEmail.Get()
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.WinsorizePct) {
		toSerialize["winsorizePct"] = o.WinsorizePct
	}
	if o.DefaultMinEffectOfInterest.IsSet() {
		toSerialize["defaultMinEffectOfInterest"] = o.DefaultMinEffectOfInterest.Get()
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListMetricsResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"folder",
		"eventName",
		"query",
		"queryIr",
		"displayName",
		"presetId",
		"unit",
		"version",
		"deletedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetricsResponseInner := _ListMetricsResponseInner{}

	err = json.Unmarshal(data, &varListMetricsResponseInner)

	if err != nil {
		return err
	}

	*o = ListMetricsResponseInner(varListMetricsResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "folder")
		delete(additionalProperties, "eventName")
		delete(additionalProperties, "query")
		delete(additionalProperties, "queryIr")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "presetId")
		delete(additionalProperties, "unit")
		delete(additionalProperties, "version")
		delete(additionalProperties, "deletedAt")
		delete(additionalProperties, "creatorEmail")
		delete(additionalProperties, "updaterEmail")
		delete(additionalProperties, "direction")
		delete(additionalProperties, "winsorizePct")
		delete(additionalProperties, "defaultMinEffectOfInterest")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListMetricsResponseInner struct {
	value *ListMetricsResponseInner
	isSet bool
}

func (v NullableListMetricsResponseInner) Get() *ListMetricsResponseInner {
	return v.value
}

func (v *NullableListMetricsResponseInner) Set(val *ListMetricsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetricsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetricsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetricsResponseInner(val *ListMetricsResponseInner) *NullableListMetricsResponseInner {
	return &NullableListMetricsResponseInner{value: val, isSet: true}
}

func (v NullableListMetricsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetricsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


