/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMetricsResponseInnerQueryIrAggOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetricsResponseInnerQueryIrAggOneOf5{}

// ListMetricsResponseInnerQueryIrAggOneOf5 struct for ListMetricsResponseInnerQueryIrAggOneOf5
type ListMetricsResponseInnerQueryIrAggOneOf5 struct {
	Kind string `json:"kind"`
}

type _ListMetricsResponseInnerQueryIrAggOneOf5 ListMetricsResponseInnerQueryIrAggOneOf5

// NewListMetricsResponseInnerQueryIrAggOneOf5 instantiates a new ListMetricsResponseInnerQueryIrAggOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetricsResponseInnerQueryIrAggOneOf5(kind string) *ListMetricsResponseInnerQueryIrAggOneOf5 {
	this := ListMetricsResponseInnerQueryIrAggOneOf5{}
	this.Kind = kind
	return &this
}

// NewListMetricsResponseInnerQueryIrAggOneOf5WithDefaults instantiates a new ListMetricsResponseInnerQueryIrAggOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetricsResponseInnerQueryIrAggOneOf5WithDefaults() *ListMetricsResponseInnerQueryIrAggOneOf5 {
	this := ListMetricsResponseInnerQueryIrAggOneOf5{}
	return &this
}

// GetKind returns the Kind field value
func (o *ListMetricsResponseInnerQueryIrAggOneOf5) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ListMetricsResponseInnerQueryIrAggOneOf5) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ListMetricsResponseInnerQueryIrAggOneOf5) SetKind(v string) {
	o.Kind = v
}

func (o ListMetricsResponseInnerQueryIrAggOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetricsResponseInnerQueryIrAggOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	return toSerialize, nil
}

func (o *ListMetricsResponseInnerQueryIrAggOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetricsResponseInnerQueryIrAggOneOf5 := _ListMetricsResponseInnerQueryIrAggOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMetricsResponseInnerQueryIrAggOneOf5)

	if err != nil {
		return err
	}

	*o = ListMetricsResponseInnerQueryIrAggOneOf5(varListMetricsResponseInnerQueryIrAggOneOf5)

	return err
}

type NullableListMetricsResponseInnerQueryIrAggOneOf5 struct {
	value *ListMetricsResponseInnerQueryIrAggOneOf5
	isSet bool
}

func (v NullableListMetricsResponseInnerQueryIrAggOneOf5) Get() *ListMetricsResponseInnerQueryIrAggOneOf5 {
	return v.value
}

func (v *NullableListMetricsResponseInnerQueryIrAggOneOf5) Set(val *ListMetricsResponseInnerQueryIrAggOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetricsResponseInnerQueryIrAggOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetricsResponseInnerQueryIrAggOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetricsResponseInnerQueryIrAggOneOf5(val *ListMetricsResponseInnerQueryIrAggOneOf5) *NullableListMetricsResponseInnerQueryIrAggOneOf5 {
	return &NullableListMetricsResponseInnerQueryIrAggOneOf5{value: val, isSet: true}
}

func (v NullableListMetricsResponseInnerQueryIrAggOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetricsResponseInnerQueryIrAggOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


