/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateKeyResponse{}

// CreateKeyResponse The minted key. The plaintext `key` is returned **once**, here — it is stored hashed and can never be retrieved again.
type CreateKeyResponse struct {
	// Stable opaque key id (UUID). Use it to revoke the key.
	Id string `json:"id"`
	// The kind of key that was minted.
	Type string `json:"type"`
	// Environment the key is bound to (`prod` for `admin`/`ops`).
	Env string `json:"env"`
	// The plaintext API token (e.g. `sdk_server_…`). Returned once — store it now; it cannot be recovered.
	Key string `json:"key"`
	// ISO-8601 expiry, or `null` if the key never expires.
	ExpiresAt NullableString `json:"expires_at"`
}

type _CreateKeyResponse CreateKeyResponse

// NewCreateKeyResponse instantiates a new CreateKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateKeyResponse(id string, type_ string, env string, key string, expiresAt NullableString) *CreateKeyResponse {
	this := CreateKeyResponse{}
	this.Id = id
	this.Type = type_
	this.Env = env
	this.Key = key
	this.ExpiresAt = expiresAt
	return &this
}

// NewCreateKeyResponseWithDefaults instantiates a new CreateKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateKeyResponseWithDefaults() *CreateKeyResponse {
	this := CreateKeyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateKeyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateKeyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateKeyResponse) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CreateKeyResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateKeyResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateKeyResponse) SetType(v string) {
	o.Type = v
}

// GetEnv returns the Env field value
func (o *CreateKeyResponse) GetEnv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *CreateKeyResponse) GetEnvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *CreateKeyResponse) SetEnv(v string) {
	o.Env = v
}

// GetKey returns the Key field value
func (o *CreateKeyResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateKeyResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateKeyResponse) SetKey(v string) {
	o.Key = v
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateKeyResponse) GetExpiresAt() string {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateKeyResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *CreateKeyResponse) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

func (o CreateKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["env"] = o.Env
	toSerialize["key"] = o.Key
	toSerialize["expires_at"] = o.ExpiresAt.Get()
	return toSerialize, nil
}

func (o *CreateKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"env",
		"key",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateKeyResponse := _CreateKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateKeyResponse)

	if err != nil {
		return err
	}

	*o = CreateKeyResponse(varCreateKeyResponse)

	return err
}

type NullableCreateKeyResponse struct {
	value *CreateKeyResponse
	isSet bool
}

func (v NullableCreateKeyResponse) Get() *CreateKeyResponse {
	return v.value
}

func (v *NullableCreateKeyResponse) Set(val *CreateKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateKeyResponse(val *CreateKeyResponse) *NullableCreateKeyResponse {
	return &NullableCreateKeyResponse{value: val, isSet: true}
}

func (v NullableCreateKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


