/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEventRequestPropertiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEventRequestPropertiesInner{}

// CreateEventRequestPropertiesInner One typed property declared on a catalogued event.
type CreateEventRequestPropertiesInner struct {
	// Property key, e.g. `amount` or `plan`. Must be a bare identifier — it is emitted as a SQL alias when the property is used as a `by()` dimension, and there is no way to quote one in the Analytics Engine dialect.
	Name string `json:"name" validate:"regexp=^[a-zA-Z_][a-zA-Z_0-9]*$"`
	// Value type of the property as recorded on the event.
	Type string `json:"type"`
	// Whether the property must be present on every emitted event.
	Required *bool `json:"required,omitempty"`
	// Human-readable description of the property.
	Description *string `json:"description,omitempty"`
}

type _CreateEventRequestPropertiesInner CreateEventRequestPropertiesInner

// NewCreateEventRequestPropertiesInner instantiates a new CreateEventRequestPropertiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventRequestPropertiesInner(name string, type_ string) *CreateEventRequestPropertiesInner {
	this := CreateEventRequestPropertiesInner{}
	this.Name = name
	this.Type = type_
	var required bool = false
	this.Required = &required
	var description string = ""
	this.Description = &description
	return &this
}

// NewCreateEventRequestPropertiesInnerWithDefaults instantiates a new CreateEventRequestPropertiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventRequestPropertiesInnerWithDefaults() *CreateEventRequestPropertiesInner {
	this := CreateEventRequestPropertiesInner{}
	var required bool = false
	this.Required = &required
	var description string = ""
	this.Description = &description
	return &this
}

// GetName returns the Name field value
func (o *CreateEventRequestPropertiesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequestPropertiesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEventRequestPropertiesInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CreateEventRequestPropertiesInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequestPropertiesInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateEventRequestPropertiesInner) SetType(v string) {
	o.Type = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *CreateEventRequestPropertiesInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestPropertiesInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *CreateEventRequestPropertiesInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *CreateEventRequestPropertiesInner) SetRequired(v bool) {
	o.Required = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateEventRequestPropertiesInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestPropertiesInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEventRequestPropertiesInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateEventRequestPropertiesInner) SetDescription(v string) {
	o.Description = &v
}

func (o CreateEventRequestPropertiesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEventRequestPropertiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateEventRequestPropertiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEventRequestPropertiesInner := _CreateEventRequestPropertiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEventRequestPropertiesInner)

	if err != nil {
		return err
	}

	*o = CreateEventRequestPropertiesInner(varCreateEventRequestPropertiesInner)

	return err
}

type NullableCreateEventRequestPropertiesInner struct {
	value *CreateEventRequestPropertiesInner
	isSet bool
}

func (v NullableCreateEventRequestPropertiesInner) Get() *CreateEventRequestPropertiesInner {
	return v.value
}

func (v *NullableCreateEventRequestPropertiesInner) Set(val *CreateEventRequestPropertiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventRequestPropertiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventRequestPropertiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventRequestPropertiesInner(val *CreateEventRequestPropertiesInner) *NullableCreateEventRequestPropertiesInner {
	return &NullableCreateEventRequestPropertiesInner{value: val, isSet: true}
}

func (v NullableCreateEventRequestPropertiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventRequestPropertiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


