/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the ListAttributesResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAttributesResponseInner{}

// ListAttributesResponseInner One declared or auto-inferred targeting attribute row.
type ListAttributesResponseInner struct {
	// Stable opaque attribute id.
	Id string `json:"id"`
	// Attribute key as seen in evaluation context (e.g. `plan`, `country`).
	Name string `json:"name"`
	Type AttributeType `json:"type"`
	// Allowed values for `enum` attributes, else `null`.
	EnumValues []string `json:"enumValues,omitempty"`
	// Whether the attribute must be present on the evaluation context (D1 stores the flag as `0`/`1`).
	Required *int32 `json:"required,omitempty"`
	// Human note shown in the dashboard, or `null`.
	Description NullableString `json:"description,omitempty"`
	// Dotted path the SDK reads the value from, or `null`.
	SdkPath NullableString `json:"sdkPath,omitempty"`
	// ISO-8601 creation timestamp.
	CreatedAt *string `json:"createdAt,omitempty"`
	// How the attribute came to exist — `auto` (inferred by the `/sdk/evaluate` sampler) or `manual` (declared via the UI/API).
	Source *string `json:"source,omitempty"`
	// ISO-8601 timestamp of the most recent SDK sample that carried this attribute, or `null` when never sampled.
	LastSeenAt NullableString `json:"lastSeenAt,omitempty"`
	// `1` when an auto-discovered attribute has stopped appearing in samples. Deprecated attributes stay listed; pickers may hide or de-rank them.
	Deprecated *int32 `json:"deprecated,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAttributesResponseInner ListAttributesResponseInner

// NewListAttributesResponseInner instantiates a new ListAttributesResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAttributesResponseInner(id string, name string, type_ AttributeType) *ListAttributesResponseInner {
	this := ListAttributesResponseInner{}
	this.Id = id
	this.Name = name
	this.Type = type_
	return &this
}

// NewListAttributesResponseInnerWithDefaults instantiates a new ListAttributesResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAttributesResponseInnerWithDefaults() *ListAttributesResponseInner {
	this := ListAttributesResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListAttributesResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListAttributesResponseInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListAttributesResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListAttributesResponseInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ListAttributesResponseInner) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ListAttributesResponseInner) SetType(v AttributeType) {
	o.Type = v
}

// GetEnumValues returns the EnumValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAttributesResponseInner) GetEnumValues() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.EnumValues
}

// GetEnumValuesOk returns a tuple with the EnumValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAttributesResponseInner) GetEnumValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.EnumValues) {
		return nil, false
	}
	return o.EnumValues, true
}

// HasEnumValues returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasEnumValues() bool {
	if o != nil && !IsNil(o.EnumValues) {
		return true
	}

	return false
}

// SetEnumValues gets a reference to the given []string and assigns it to the EnumValues field.
func (o *ListAttributesResponseInner) SetEnumValues(v []string) {
	o.EnumValues = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ListAttributesResponseInner) GetRequired() int32 {
	if o == nil || IsNil(o.Required) {
		var ret int32
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetRequiredOk() (*int32, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given int32 and assigns it to the Required field.
func (o *ListAttributesResponseInner) SetRequired(v int32) {
	o.Required = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAttributesResponseInner) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAttributesResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ListAttributesResponseInner) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ListAttributesResponseInner) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ListAttributesResponseInner) UnsetDescription() {
	o.Description.Unset()
}

// GetSdkPath returns the SdkPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAttributesResponseInner) GetSdkPath() string {
	if o == nil || IsNil(o.SdkPath.Get()) {
		var ret string
		return ret
	}
	return *o.SdkPath.Get()
}

// GetSdkPathOk returns a tuple with the SdkPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAttributesResponseInner) GetSdkPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SdkPath.Get(), o.SdkPath.IsSet()
}

// HasSdkPath returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasSdkPath() bool {
	if o != nil && o.SdkPath.IsSet() {
		return true
	}

	return false
}

// SetSdkPath gets a reference to the given NullableString and assigns it to the SdkPath field.
func (o *ListAttributesResponseInner) SetSdkPath(v string) {
	o.SdkPath.Set(&v)
}
// SetSdkPathNil sets the value for SdkPath to be an explicit nil
func (o *ListAttributesResponseInner) SetSdkPathNil() {
	o.SdkPath.Set(nil)
}

// UnsetSdkPath ensures that no value is present for SdkPath, not even an explicit nil
func (o *ListAttributesResponseInner) UnsetSdkPath() {
	o.SdkPath.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListAttributesResponseInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ListAttributesResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ListAttributesResponseInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *ListAttributesResponseInner) SetSource(v string) {
	o.Source = &v
}

// GetLastSeenAt returns the LastSeenAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAttributesResponseInner) GetLastSeenAt() string {
	if o == nil || IsNil(o.LastSeenAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastSeenAt.Get()
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAttributesResponseInner) GetLastSeenAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSeenAt.Get(), o.LastSeenAt.IsSet()
}

// HasLastSeenAt returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasLastSeenAt() bool {
	if o != nil && o.LastSeenAt.IsSet() {
		return true
	}

	return false
}

// SetLastSeenAt gets a reference to the given NullableString and assigns it to the LastSeenAt field.
func (o *ListAttributesResponseInner) SetLastSeenAt(v string) {
	o.LastSeenAt.Set(&v)
}
// SetLastSeenAtNil sets the value for LastSeenAt to be an explicit nil
func (o *ListAttributesResponseInner) SetLastSeenAtNil() {
	o.LastSeenAt.Set(nil)
}

// UnsetLastSeenAt ensures that no value is present for LastSeenAt, not even an explicit nil
func (o *ListAttributesResponseInner) UnsetLastSeenAt() {
	o.LastSeenAt.Unset()
}

// GetDeprecated returns the Deprecated field value if set, zero value otherwise.
func (o *ListAttributesResponseInner) GetDeprecated() int32 {
	if o == nil || IsNil(o.Deprecated) {
		var ret int32
		return ret
	}
	return *o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAttributesResponseInner) GetDeprecatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Deprecated) {
		return nil, false
	}
	return o.Deprecated, true
}

// HasDeprecated returns a boolean if a field has been set.
func (o *ListAttributesResponseInner) HasDeprecated() bool {
	if o != nil && !IsNil(o.Deprecated) {
		return true
	}

	return false
}

// SetDeprecated gets a reference to the given int32 and assigns it to the Deprecated field.
func (o *ListAttributesResponseInner) SetDeprecated(v int32) {
	o.Deprecated = &v
}

func (o ListAttributesResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAttributesResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if o.EnumValues != nil {
		toSerialize["enumValues"] = o.EnumValues
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SdkPath.IsSet() {
		toSerialize["sdkPath"] = o.SdkPath.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if o.LastSeenAt.IsSet() {
		toSerialize["lastSeenAt"] = o.LastSeenAt.Get()
	}
	if !IsNil(o.Deprecated) {
		toSerialize["deprecated"] = o.Deprecated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAttributesResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAttributesResponseInner := _ListAttributesResponseInner{}

	err = json.Unmarshal(data, &varListAttributesResponseInner)

	if err != nil {
		return err
	}

	*o = ListAttributesResponseInner(varListAttributesResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "enumValues")
		delete(additionalProperties, "required")
		delete(additionalProperties, "description")
		delete(additionalProperties, "sdkPath")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "source")
		delete(additionalProperties, "lastSeenAt")
		delete(additionalProperties, "deprecated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAttributesResponseInner struct {
	value *ListAttributesResponseInner
	isSet bool
}

func (v NullableListAttributesResponseInner) Get() *ListAttributesResponseInner {
	return v.value
}

func (v *NullableListAttributesResponseInner) Set(val *ListAttributesResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListAttributesResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListAttributesResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAttributesResponseInner(val *ListAttributesResponseInner) *NullableListAttributesResponseInner {
	return &NullableListAttributesResponseInner{value: val, isSet: true}
}

func (v NullableListAttributesResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAttributesResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


