/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveEventResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveEventResponse{}

// ApproveEventResponse Result of updating or approving an event.
type ApproveEventResponse struct {
	// Event id that was updated.
	Id string `json:"id"`
}

type _ApproveEventResponse ApproveEventResponse

// NewApproveEventResponse instantiates a new ApproveEventResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveEventResponse(id string) *ApproveEventResponse {
	this := ApproveEventResponse{}
	this.Id = id
	return &this
}

// NewApproveEventResponseWithDefaults instantiates a new ApproveEventResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveEventResponseWithDefaults() *ApproveEventResponse {
	this := ApproveEventResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ApproveEventResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApproveEventResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApproveEventResponse) SetId(v string) {
	o.Id = v
}

func (o ApproveEventResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveEventResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ApproveEventResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveEventResponse := _ApproveEventResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveEventResponse)

	if err != nil {
		return err
	}

	*o = ApproveEventResponse(varApproveEventResponse)

	return err
}

type NullableApproveEventResponse struct {
	value *ApproveEventResponse
	isSet bool
}

func (v NullableApproveEventResponse) Get() *ApproveEventResponse {
	return v.value
}

func (v *NullableApproveEventResponse) Set(val *ApproveEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveEventResponse(val *ApproveEventResponse) *NullableApproveEventResponse {
	return &NullableApproveEventResponse{value: val, isSet: true}
}

func (v NullableApproveEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


