/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// MetricDirection Desired direction of movement. `higher_better` (default), `lower_better`, or `neutral` (guardrail).
type MetricDirection string

// List of MetricDirection
const (
	METRICDIRECTION_HIGHER_BETTER MetricDirection = "higher_better"
	METRICDIRECTION_LOWER_BETTER MetricDirection = "lower_better"
	METRICDIRECTION_NEUTRAL MetricDirection = "neutral"
)

// All allowed values of MetricDirection enum
var AllowedMetricDirectionEnumValues = []MetricDirection{
	"higher_better",
	"lower_better",
	"neutral",
}

func (v *MetricDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MetricDirection(value)
	for _, existing := range AllowedMetricDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MetricDirection", value)
}

// NewMetricDirectionFromValue returns a pointer to a valid MetricDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMetricDirectionFromValue(v string) (*MetricDirection, error) {
	ev := MetricDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MetricDirection: valid values are %v", v, AllowedMetricDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MetricDirection) IsValid() bool {
	for _, existing := range AllowedMetricDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MetricDirection value
func (v MetricDirection) Ptr() *MetricDirection {
	return &v
}

type NullableMetricDirection struct {
	value *MetricDirection
	isSet bool
}

func (v NullableMetricDirection) Get() *MetricDirection {
	return v.value
}

func (v *NullableMetricDirection) Set(val *MetricDirection) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricDirection) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricDirection(val *MetricDirection) *NullableMetricDirection {
	return &NullableMetricDirection{value: val, isSet: true}
}

func (v NullableMetricDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

