/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OkResponse{}

// OkResponse Generic success acknowledgement for operations with no meaningful payload.
type OkResponse struct {
	// Always `true` — the operation succeeded (errors use the error envelope instead).
	Ok bool `json:"ok"`
}

type _OkResponse OkResponse

// NewOkResponse instantiates a new OkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOkResponse(ok bool) *OkResponse {
	this := OkResponse{}
	this.Ok = ok
	return &this
}

// NewOkResponseWithDefaults instantiates a new OkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOkResponseWithDefaults() *OkResponse {
	this := OkResponse{}
	return &this
}

// GetOk returns the Ok field value
func (o *OkResponse) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *OkResponse) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *OkResponse) SetOk(v bool) {
	o.Ok = v
}

func (o OkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ok"] = o.Ok
	return toSerialize, nil
}

func (o *OkResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ok",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOkResponse := _OkResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOkResponse)

	if err != nil {
		return err
	}

	*o = OkResponse(varOkResponse)

	return err
}

type NullableOkResponse struct {
	value *OkResponse
	isSet bool
}

func (v NullableOkResponse) Get() *OkResponse {
	return v.value
}

func (v *NullableOkResponse) Set(val *OkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOkResponse(val *OkResponse) *NullableOkResponse {
	return &NullableOkResponse{value: val, isSet: true}
}

func (v NullableOkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


