/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetI18nLabelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetI18nLabelRequest{}

// SetI18nLabelRequest Body for `POST /api/admin/i18n/set`. Upserts one key's value and publishes the profile live.
type SetI18nLabelRequest struct {
	// Dotted key path to set, e.g. `home.cta`.
	Key string `json:"key"`
	// New value for the key. Inserted when the key is new, overwritten when it exists.
	Value string `json:"value"`
	// Profile name to target, e.g. `en:prod`. Omit to target the project's default-marked profile.
	Profile *string `json:"profile,omitempty"`
	// Optional human note to store with the key.
	Description *string `json:"description,omitempty"`
}

type _SetI18nLabelRequest SetI18nLabelRequest

// NewSetI18nLabelRequest instantiates a new SetI18nLabelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetI18nLabelRequest(key string, value string) *SetI18nLabelRequest {
	this := SetI18nLabelRequest{}
	this.Key = key
	this.Value = value
	return &this
}

// NewSetI18nLabelRequestWithDefaults instantiates a new SetI18nLabelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetI18nLabelRequestWithDefaults() *SetI18nLabelRequest {
	this := SetI18nLabelRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *SetI18nLabelRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *SetI18nLabelRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SetI18nLabelRequest) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *SetI18nLabelRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SetI18nLabelRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SetI18nLabelRequest) SetValue(v string) {
	o.Value = v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *SetI18nLabelRequest) GetProfile() string {
	if o == nil || IsNil(o.Profile) {
		var ret string
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetI18nLabelRequest) GetProfileOk() (*string, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *SetI18nLabelRequest) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given string and assigns it to the Profile field.
func (o *SetI18nLabelRequest) SetProfile(v string) {
	o.Profile = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SetI18nLabelRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetI18nLabelRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SetI18nLabelRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SetI18nLabelRequest) SetDescription(v string) {
	o.Description = &v
}

func (o SetI18nLabelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetI18nLabelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *SetI18nLabelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetI18nLabelRequest := _SetI18nLabelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetI18nLabelRequest)

	if err != nil {
		return err
	}

	*o = SetI18nLabelRequest(varSetI18nLabelRequest)

	return err
}

type NullableSetI18nLabelRequest struct {
	value *SetI18nLabelRequest
	isSet bool
}

func (v NullableSetI18nLabelRequest) Get() *SetI18nLabelRequest {
	return v.value
}

func (v *NullableSetI18nLabelRequest) Set(val *SetI18nLabelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetI18nLabelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetI18nLabelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetI18nLabelRequest(val *SetI18nLabelRequest) *NullableSetI18nLabelRequest {
	return &NullableSetI18nLabelRequest{value: val, isSet: true}
}

func (v NullableSetI18nLabelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetI18nLabelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


