/*
Shipeasy Admin API (server-SDK surface)

The slice of the Shipeasy admin API that the published server SDKs expose as their optional `AdminClient`. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Three capabilities, nothing else:  - **File a public ticket** — a bug or a feature request onto the project's ops queue. - **Toggle a kill switch** — flip the switch itself, or one of its named sub-switches, on one environment. - **Manage a flag's whitelist** — read, replace, add to, or remove from the allowlist that admits specific identities ahead of every targeting rule.  Everything else in the admin API is reachable through the Shipeasy CLI and MCP server, which speak the complete contract (`openapi.yaml`).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveFromGateWhitelistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveFromGateWhitelistRequest{}

// RemoveFromGateWhitelistRequest Body for `DELETE /api/admin/gates/{id}/whitelist`. Removes entries from the whitelist. Removing the last entry leaves an empty whitelist in place — use `PUT` with `entries: []` to drop the block itself.
type RemoveFromGateWhitelistRequest struct {
	// Identities to stop admitting. Entries that aren't listed are skipped, so the call is idempotent.
	Entries []string `json:"entries"`
}

type _RemoveFromGateWhitelistRequest RemoveFromGateWhitelistRequest

// NewRemoveFromGateWhitelistRequest instantiates a new RemoveFromGateWhitelistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveFromGateWhitelistRequest(entries []string) *RemoveFromGateWhitelistRequest {
	this := RemoveFromGateWhitelistRequest{}
	this.Entries = entries
	return &this
}

// NewRemoveFromGateWhitelistRequestWithDefaults instantiates a new RemoveFromGateWhitelistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveFromGateWhitelistRequestWithDefaults() *RemoveFromGateWhitelistRequest {
	this := RemoveFromGateWhitelistRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *RemoveFromGateWhitelistRequest) GetEntries() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *RemoveFromGateWhitelistRequest) GetEntriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *RemoveFromGateWhitelistRequest) SetEntries(v []string) {
	o.Entries = v
}

func (o RemoveFromGateWhitelistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveFromGateWhitelistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *RemoveFromGateWhitelistRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveFromGateWhitelistRequest := _RemoveFromGateWhitelistRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveFromGateWhitelistRequest)

	if err != nil {
		return err
	}

	*o = RemoveFromGateWhitelistRequest(varRemoveFromGateWhitelistRequest)

	return err
}

type NullableRemoveFromGateWhitelistRequest struct {
	value *RemoveFromGateWhitelistRequest
	isSet bool
}

func (v NullableRemoveFromGateWhitelistRequest) Get() *RemoveFromGateWhitelistRequest {
	return v.value
}

func (v *NullableRemoveFromGateWhitelistRequest) Set(val *RemoveFromGateWhitelistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveFromGateWhitelistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveFromGateWhitelistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveFromGateWhitelistRequest(val *RemoveFromGateWhitelistRequest) *NullableRemoveFromGateWhitelistRequest {
	return &NullableRemoveFromGateWhitelistRequest{value: val, isSet: true}
}

func (v NullableRemoveFromGateWhitelistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveFromGateWhitelistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


