/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GateApiRowStackInnerOneOfRamp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GateApiRowStackInnerOneOfRamp{}

// GateApiRowStackInnerOneOfRamp Linear rollout ramp. The effective rollout % interpolates `from`→`to` over `[startAt, startAt+durationMs]`, clamped outside that window, evaluated against the wall-clock at eval time. Overrides the entry's static `rolloutPct` while present.
type GateApiRowStackInnerOneOfRamp struct {
	// Start of the ramp in basis points (0–10000).
	From int32 `json:"from"`
	// End of the ramp in basis points (0–10000).
	To int32 `json:"to"`
	// Ramp start, epoch milliseconds (UTC).
	StartAt int32 `json:"startAt"`
	// Ramp length in milliseconds.
	DurationMs int32 `json:"durationMs"`
}

type _GateApiRowStackInnerOneOfRamp GateApiRowStackInnerOneOfRamp

// NewGateApiRowStackInnerOneOfRamp instantiates a new GateApiRowStackInnerOneOfRamp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGateApiRowStackInnerOneOfRamp(from int32, to int32, startAt int32, durationMs int32) *GateApiRowStackInnerOneOfRamp {
	this := GateApiRowStackInnerOneOfRamp{}
	this.From = from
	this.To = to
	this.StartAt = startAt
	this.DurationMs = durationMs
	return &this
}

// NewGateApiRowStackInnerOneOfRampWithDefaults instantiates a new GateApiRowStackInnerOneOfRamp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGateApiRowStackInnerOneOfRampWithDefaults() *GateApiRowStackInnerOneOfRamp {
	this := GateApiRowStackInnerOneOfRamp{}
	return &this
}

// GetFrom returns the From field value
func (o *GateApiRowStackInnerOneOfRamp) GetFrom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *GateApiRowStackInnerOneOfRamp) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *GateApiRowStackInnerOneOfRamp) SetFrom(v int32) {
	o.From = v
}

// GetTo returns the To field value
func (o *GateApiRowStackInnerOneOfRamp) GetTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *GateApiRowStackInnerOneOfRamp) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *GateApiRowStackInnerOneOfRamp) SetTo(v int32) {
	o.To = v
}

// GetStartAt returns the StartAt field value
func (o *GateApiRowStackInnerOneOfRamp) GetStartAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *GateApiRowStackInnerOneOfRamp) GetStartAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *GateApiRowStackInnerOneOfRamp) SetStartAt(v int32) {
	o.StartAt = v
}

// GetDurationMs returns the DurationMs field value
func (o *GateApiRowStackInnerOneOfRamp) GetDurationMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value
// and a boolean to check if the value has been set.
func (o *GateApiRowStackInnerOneOfRamp) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMs, true
}

// SetDurationMs sets field value
func (o *GateApiRowStackInnerOneOfRamp) SetDurationMs(v int32) {
	o.DurationMs = v
}

func (o GateApiRowStackInnerOneOfRamp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GateApiRowStackInnerOneOfRamp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["startAt"] = o.StartAt
	toSerialize["durationMs"] = o.DurationMs
	return toSerialize, nil
}

func (o *GateApiRowStackInnerOneOfRamp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"startAt",
		"durationMs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGateApiRowStackInnerOneOfRamp := _GateApiRowStackInnerOneOfRamp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGateApiRowStackInnerOneOfRamp)

	if err != nil {
		return err
	}

	*o = GateApiRowStackInnerOneOfRamp(varGateApiRowStackInnerOneOfRamp)

	return err
}

type NullableGateApiRowStackInnerOneOfRamp struct {
	value *GateApiRowStackInnerOneOfRamp
	isSet bool
}

func (v NullableGateApiRowStackInnerOneOfRamp) Get() *GateApiRowStackInnerOneOfRamp {
	return v.value
}

func (v *NullableGateApiRowStackInnerOneOfRamp) Set(val *GateApiRowStackInnerOneOfRamp) {
	v.value = val
	v.isSet = true
}

func (v NullableGateApiRowStackInnerOneOfRamp) IsSet() bool {
	return v.isSet
}

func (v *NullableGateApiRowStackInnerOneOfRamp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGateApiRowStackInnerOneOfRamp(val *GateApiRowStackInnerOneOfRamp) *NullableGateApiRowStackInnerOneOfRamp {
	return &NullableGateApiRowStackInnerOneOfRamp{value: val, isSet: true}
}

func (v NullableGateApiRowStackInnerOneOfRamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGateApiRowStackInnerOneOfRamp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


