/*
Shipeasy Admin API (SDK admin subset)

Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"fmt"
)

// checks if the OpsItemAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpsItemAttachment{}

// OpsItemAttachment A file uploaded with a bug/feature report.
type OpsItemAttachment struct {
	// Attachment id.
	Id string `json:"id"`
	// `screenshot` | `video` | `log`.
	Kind string `json:"kind"`
	// Sanitized original filename.
	Filename string `json:"filename"`
	// MIME type, e.g. `image/png`.
	MimeType string `json:"mimeType"`
	// Upload size in bytes.
	SizeBytes float32 `json:"sizeBytes"`
	// Admin-API path to download the file (`GET` with the admin/ops key — screenshots render inline; recordings can't be watched).
	FetchUrl string `json:"fetchUrl"`
	AdditionalProperties map[string]interface{}
}

type _OpsItemAttachment OpsItemAttachment

// NewOpsItemAttachment instantiates a new OpsItemAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsItemAttachment(id string, kind string, filename string, mimeType string, sizeBytes float32, fetchUrl string) *OpsItemAttachment {
	this := OpsItemAttachment{}
	this.Id = id
	this.Kind = kind
	this.Filename = filename
	this.MimeType = mimeType
	this.SizeBytes = sizeBytes
	this.FetchUrl = fetchUrl
	return &this
}

// NewOpsItemAttachmentWithDefaults instantiates a new OpsItemAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsItemAttachmentWithDefaults() *OpsItemAttachment {
	this := OpsItemAttachment{}
	return &this
}

// GetId returns the Id field value
func (o *OpsItemAttachment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpsItemAttachment) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *OpsItemAttachment) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *OpsItemAttachment) SetKind(v string) {
	o.Kind = v
}

// GetFilename returns the Filename field value
func (o *OpsItemAttachment) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *OpsItemAttachment) SetFilename(v string) {
	o.Filename = v
}

// GetMimeType returns the MimeType field value
func (o *OpsItemAttachment) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *OpsItemAttachment) SetMimeType(v string) {
	o.MimeType = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *OpsItemAttachment) GetSizeBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetSizeBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *OpsItemAttachment) SetSizeBytes(v float32) {
	o.SizeBytes = v
}

// GetFetchUrl returns the FetchUrl field value
func (o *OpsItemAttachment) GetFetchUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FetchUrl
}

// GetFetchUrlOk returns a tuple with the FetchUrl field value
// and a boolean to check if the value has been set.
func (o *OpsItemAttachment) GetFetchUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FetchUrl, true
}

// SetFetchUrl sets field value
func (o *OpsItemAttachment) SetFetchUrl(v string) {
	o.FetchUrl = v
}

func (o OpsItemAttachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpsItemAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["filename"] = o.Filename
	toSerialize["mimeType"] = o.MimeType
	toSerialize["sizeBytes"] = o.SizeBytes
	toSerialize["fetchUrl"] = o.FetchUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpsItemAttachment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"kind",
		"filename",
		"mimeType",
		"sizeBytes",
		"fetchUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpsItemAttachment := _OpsItemAttachment{}

	err = json.Unmarshal(data, &varOpsItemAttachment)

	if err != nil {
		return err
	}

	*o = OpsItemAttachment(varOpsItemAttachment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "filename")
		delete(additionalProperties, "mimeType")
		delete(additionalProperties, "sizeBytes")
		delete(additionalProperties, "fetchUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpsItemAttachment struct {
	value *OpsItemAttachment
	isSet bool
}

func (v NullableOpsItemAttachment) Get() *OpsItemAttachment {
	return v.value
}

func (v *NullableOpsItemAttachment) Set(val *OpsItemAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsItemAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsItemAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsItemAttachment(val *OpsItemAttachment) *NullableOpsItemAttachment {
	return &NullableOpsItemAttachment{value: val, isSet: true}
}

func (v NullableOpsItemAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsItemAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


