/*
Shipeasy Admin API

REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListSlackChannelsResponseChannelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSlackChannelsResponseChannelsInner{}

// ListSlackChannelsResponseChannelsInner One Slack channel the project can post to.
type ListSlackChannelsResponseChannelsInner struct {
	// Slack channel id.
	Id string `json:"id"`
	// Slack channel name (without the leading `#`).
	Name string `json:"name"`
	// Whether the channel is private.
	IsPrivate *bool `json:"isPrivate,omitempty"`
}

type _ListSlackChannelsResponseChannelsInner ListSlackChannelsResponseChannelsInner

// NewListSlackChannelsResponseChannelsInner instantiates a new ListSlackChannelsResponseChannelsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSlackChannelsResponseChannelsInner(id string, name string) *ListSlackChannelsResponseChannelsInner {
	this := ListSlackChannelsResponseChannelsInner{}
	this.Id = id
	this.Name = name
	return &this
}

// NewListSlackChannelsResponseChannelsInnerWithDefaults instantiates a new ListSlackChannelsResponseChannelsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSlackChannelsResponseChannelsInnerWithDefaults() *ListSlackChannelsResponseChannelsInner {
	this := ListSlackChannelsResponseChannelsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListSlackChannelsResponseChannelsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListSlackChannelsResponseChannelsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListSlackChannelsResponseChannelsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListSlackChannelsResponseChannelsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListSlackChannelsResponseChannelsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListSlackChannelsResponseChannelsInner) SetName(v string) {
	o.Name = v
}

// GetIsPrivate returns the IsPrivate field value if set, zero value otherwise.
func (o *ListSlackChannelsResponseChannelsInner) GetIsPrivate() bool {
	if o == nil || IsNil(o.IsPrivate) {
		var ret bool
		return ret
	}
	return *o.IsPrivate
}

// GetIsPrivateOk returns a tuple with the IsPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSlackChannelsResponseChannelsInner) GetIsPrivateOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrivate) {
		return nil, false
	}
	return o.IsPrivate, true
}

// HasIsPrivate returns a boolean if a field has been set.
func (o *ListSlackChannelsResponseChannelsInner) HasIsPrivate() bool {
	if o != nil && !IsNil(o.IsPrivate) {
		return true
	}

	return false
}

// SetIsPrivate gets a reference to the given bool and assigns it to the IsPrivate field.
func (o *ListSlackChannelsResponseChannelsInner) SetIsPrivate(v bool) {
	o.IsPrivate = &v
}

func (o ListSlackChannelsResponseChannelsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSlackChannelsResponseChannelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.IsPrivate) {
		toSerialize["isPrivate"] = o.IsPrivate
	}
	return toSerialize, nil
}

func (o *ListSlackChannelsResponseChannelsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListSlackChannelsResponseChannelsInner := _ListSlackChannelsResponseChannelsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListSlackChannelsResponseChannelsInner)

	if err != nil {
		return err
	}

	*o = ListSlackChannelsResponseChannelsInner(varListSlackChannelsResponseChannelsInner)

	return err
}

type NullableListSlackChannelsResponseChannelsInner struct {
	value *ListSlackChannelsResponseChannelsInner
	isSet bool
}

func (v NullableListSlackChannelsResponseChannelsInner) Get() *ListSlackChannelsResponseChannelsInner {
	return v.value
}

func (v *NullableListSlackChannelsResponseChannelsInner) Set(val *ListSlackChannelsResponseChannelsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListSlackChannelsResponseChannelsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListSlackChannelsResponseChannelsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSlackChannelsResponseChannelsInner(val *ListSlackChannelsResponseChannelsInner) *NullableListSlackChannelsResponseChannelsInner {
	return &NullableListSlackChannelsResponseChannelsInner{value: val, isSet: true}
}

func (v NullableListSlackChannelsResponseChannelsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSlackChannelsResponseChannelsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


