/*
Shipeasy Admin API (SDK admin subset)

Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateFeatureRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFeatureRequestRequest{}

// CreateFeatureRequestRequest Feature-request-kind fields for `POST /api/admin/ops` (sent with `type: feature_request`).
type CreateFeatureRequestRequest struct {
	// Discriminator — files a feature request.
	Type string `json:"type"`
	// One-line feature-request title (no leading/trailing whitespace).
	Title string `json:"title" validate:"regexp=^\\\\S(.*\\\\S)?$"`
	// What the feature is.
	Description *string `json:"description,omitempty"`
	// Why it's needed / the use case.
	UseCase *string `json:"useCase,omitempty"`
	// Initial triage priority, or `null`.
	Priority NullableOpsItemPriority `json:"priority,omitempty"`
	// Initial lifecycle status; defaults to `open` when omitted.
	Status *OpsItemStatus `json:"status,omitempty"`
	// The `users.id` of the person to assign as owner at creation, or `null`.
	AssigneeId NullableString `json:"assigneeId,omitempty"`
	// Emails of teammates to subscribe to this item's Slack pings at creation.
	Subscribers []string `json:"subscribers,omitempty"`
	// Tag names to attach at creation (get-or-created by name, deduped case-insensitively).
	Tags []string `json:"tags,omitempty"`
	// Email of the reporter, or `null`.
	ReporterEmail NullableString `json:"reporterEmail,omitempty"`
	// URL of the page the request relates to, or `null`.
	PageUrl NullableString `json:"pageUrl,omitempty"`
	// Reporter's user-agent string, or `null`.
	UserAgent NullableString `json:"userAgent,omitempty"`
	// Arbitrary capture context, or `null`.
	Context map[string]interface{} `json:"context,omitempty"`
	// Where this request's completion notification lands.
	Notify NullableNotificationTarget `json:"notify,omitempty"`
}

type _CreateFeatureRequestRequest CreateFeatureRequestRequest

// NewCreateFeatureRequestRequest instantiates a new CreateFeatureRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFeatureRequestRequest(type_ string, title string) *CreateFeatureRequestRequest {
	this := CreateFeatureRequestRequest{}
	this.Type = type_
	this.Title = title
	var description string = ""
	this.Description = &description
	var useCase string = ""
	this.UseCase = &useCase
	return &this
}

// NewCreateFeatureRequestRequestWithDefaults instantiates a new CreateFeatureRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFeatureRequestRequestWithDefaults() *CreateFeatureRequestRequest {
	this := CreateFeatureRequestRequest{}
	var description string = ""
	this.Description = &description
	var useCase string = ""
	this.UseCase = &useCase
	return &this
}

// GetType returns the Type field value
func (o *CreateFeatureRequestRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateFeatureRequestRequest) SetType(v string) {
	o.Type = v
}

// GetTitle returns the Title field value
func (o *CreateFeatureRequestRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateFeatureRequestRequest) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateFeatureRequestRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateFeatureRequestRequest) SetDescription(v string) {
	o.Description = &v
}

// GetUseCase returns the UseCase field value if set, zero value otherwise.
func (o *CreateFeatureRequestRequest) GetUseCase() string {
	if o == nil || IsNil(o.UseCase) {
		var ret string
		return ret
	}
	return *o.UseCase
}

// GetUseCaseOk returns a tuple with the UseCase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetUseCaseOk() (*string, bool) {
	if o == nil || IsNil(o.UseCase) {
		return nil, false
	}
	return o.UseCase, true
}

// HasUseCase returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasUseCase() bool {
	if o != nil && !IsNil(o.UseCase) {
		return true
	}

	return false
}

// SetUseCase gets a reference to the given string and assigns it to the UseCase field.
func (o *CreateFeatureRequestRequest) SetUseCase(v string) {
	o.UseCase = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetPriority() OpsItemPriority {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret OpsItemPriority
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetPriorityOk() (*OpsItemPriority, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableOpsItemPriority and assigns it to the Priority field.
func (o *CreateFeatureRequestRequest) SetPriority(v OpsItemPriority) {
	o.Priority.Set(&v)
}
// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *CreateFeatureRequestRequest) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetPriority() {
	o.Priority.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateFeatureRequestRequest) GetStatus() OpsItemStatus {
	if o == nil || IsNil(o.Status) {
		var ret OpsItemStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetStatusOk() (*OpsItemStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OpsItemStatus and assigns it to the Status field.
func (o *CreateFeatureRequestRequest) SetStatus(v OpsItemStatus) {
	o.Status = &v
}

// GetAssigneeId returns the AssigneeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetAssigneeId() string {
	if o == nil || IsNil(o.AssigneeId.Get()) {
		var ret string
		return ret
	}
	return *o.AssigneeId.Get()
}

// GetAssigneeIdOk returns a tuple with the AssigneeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetAssigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssigneeId.Get(), o.AssigneeId.IsSet()
}

// HasAssigneeId returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasAssigneeId() bool {
	if o != nil && o.AssigneeId.IsSet() {
		return true
	}

	return false
}

// SetAssigneeId gets a reference to the given NullableString and assigns it to the AssigneeId field.
func (o *CreateFeatureRequestRequest) SetAssigneeId(v string) {
	o.AssigneeId.Set(&v)
}
// SetAssigneeIdNil sets the value for AssigneeId to be an explicit nil
func (o *CreateFeatureRequestRequest) SetAssigneeIdNil() {
	o.AssigneeId.Set(nil)
}

// UnsetAssigneeId ensures that no value is present for AssigneeId, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetAssigneeId() {
	o.AssigneeId.Unset()
}

// GetSubscribers returns the Subscribers field value if set, zero value otherwise.
func (o *CreateFeatureRequestRequest) GetSubscribers() []string {
	if o == nil || IsNil(o.Subscribers) {
		var ret []string
		return ret
	}
	return o.Subscribers
}

// GetSubscribersOk returns a tuple with the Subscribers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetSubscribersOk() ([]string, bool) {
	if o == nil || IsNil(o.Subscribers) {
		return nil, false
	}
	return o.Subscribers, true
}

// HasSubscribers returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasSubscribers() bool {
	if o != nil && !IsNil(o.Subscribers) {
		return true
	}

	return false
}

// SetSubscribers gets a reference to the given []string and assigns it to the Subscribers field.
func (o *CreateFeatureRequestRequest) SetSubscribers(v []string) {
	o.Subscribers = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateFeatureRequestRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFeatureRequestRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateFeatureRequestRequest) SetTags(v []string) {
	o.Tags = v
}

// GetReporterEmail returns the ReporterEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetReporterEmail() string {
	if o == nil || IsNil(o.ReporterEmail.Get()) {
		var ret string
		return ret
	}
	return *o.ReporterEmail.Get()
}

// GetReporterEmailOk returns a tuple with the ReporterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetReporterEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReporterEmail.Get(), o.ReporterEmail.IsSet()
}

// HasReporterEmail returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasReporterEmail() bool {
	if o != nil && o.ReporterEmail.IsSet() {
		return true
	}

	return false
}

// SetReporterEmail gets a reference to the given NullableString and assigns it to the ReporterEmail field.
func (o *CreateFeatureRequestRequest) SetReporterEmail(v string) {
	o.ReporterEmail.Set(&v)
}
// SetReporterEmailNil sets the value for ReporterEmail to be an explicit nil
func (o *CreateFeatureRequestRequest) SetReporterEmailNil() {
	o.ReporterEmail.Set(nil)
}

// UnsetReporterEmail ensures that no value is present for ReporterEmail, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetReporterEmail() {
	o.ReporterEmail.Unset()
}

// GetPageUrl returns the PageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetPageUrl() string {
	if o == nil || IsNil(o.PageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PageUrl.Get()
}

// GetPageUrlOk returns a tuple with the PageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageUrl.Get(), o.PageUrl.IsSet()
}

// HasPageUrl returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasPageUrl() bool {
	if o != nil && o.PageUrl.IsSet() {
		return true
	}

	return false
}

// SetPageUrl gets a reference to the given NullableString and assigns it to the PageUrl field.
func (o *CreateFeatureRequestRequest) SetPageUrl(v string) {
	o.PageUrl.Set(&v)
}
// SetPageUrlNil sets the value for PageUrl to be an explicit nil
func (o *CreateFeatureRequestRequest) SetPageUrlNil() {
	o.PageUrl.Set(nil)
}

// UnsetPageUrl ensures that no value is present for PageUrl, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetPageUrl() {
	o.PageUrl.Unset()
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent.Get()) {
		var ret string
		return ret
	}
	return *o.UserAgent.Get()
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserAgent.Get(), o.UserAgent.IsSet()
}

// HasUserAgent returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasUserAgent() bool {
	if o != nil && o.UserAgent.IsSet() {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given NullableString and assigns it to the UserAgent field.
func (o *CreateFeatureRequestRequest) SetUserAgent(v string) {
	o.UserAgent.Set(&v)
}
// SetUserAgentNil sets the value for UserAgent to be an explicit nil
func (o *CreateFeatureRequestRequest) SetUserAgentNil() {
	o.UserAgent.Set(nil)
}

// UnsetUserAgent ensures that no value is present for UserAgent, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetUserAgent() {
	o.UserAgent.Unset()
}

// GetContext returns the Context field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetContext() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return map[string]interface{}{}, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *CreateFeatureRequestRequest) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetNotify returns the Notify field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateFeatureRequestRequest) GetNotify() NotificationTarget {
	if o == nil || IsNil(o.Notify.Get()) {
		var ret NotificationTarget
		return ret
	}
	return *o.Notify.Get()
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateFeatureRequestRequest) GetNotifyOk() (*NotificationTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notify.Get(), o.Notify.IsSet()
}

// HasNotify returns a boolean if a field has been set.
func (o *CreateFeatureRequestRequest) HasNotify() bool {
	if o != nil && o.Notify.IsSet() {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NullableNotificationTarget and assigns it to the Notify field.
func (o *CreateFeatureRequestRequest) SetNotify(v NotificationTarget) {
	o.Notify.Set(&v)
}
// SetNotifyNil sets the value for Notify to be an explicit nil
func (o *CreateFeatureRequestRequest) SetNotifyNil() {
	o.Notify.Set(nil)
}

// UnsetNotify ensures that no value is present for Notify, not even an explicit nil
func (o *CreateFeatureRequestRequest) UnsetNotify() {
	o.Notify.Unset()
}

func (o CreateFeatureRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFeatureRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.UseCase) {
		toSerialize["useCase"] = o.UseCase
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.AssigneeId.IsSet() {
		toSerialize["assigneeId"] = o.AssigneeId.Get()
	}
	if !IsNil(o.Subscribers) {
		toSerialize["subscribers"] = o.Subscribers
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.ReporterEmail.IsSet() {
		toSerialize["reporterEmail"] = o.ReporterEmail.Get()
	}
	if o.PageUrl.IsSet() {
		toSerialize["pageUrl"] = o.PageUrl.Get()
	}
	if o.UserAgent.IsSet() {
		toSerialize["userAgent"] = o.UserAgent.Get()
	}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if o.Notify.IsSet() {
		toSerialize["notify"] = o.Notify.Get()
	}
	return toSerialize, nil
}

func (o *CreateFeatureRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFeatureRequestRequest := _CreateFeatureRequestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFeatureRequestRequest)

	if err != nil {
		return err
	}

	*o = CreateFeatureRequestRequest(varCreateFeatureRequestRequest)

	return err
}

type NullableCreateFeatureRequestRequest struct {
	value *CreateFeatureRequestRequest
	isSet bool
}

func (v NullableCreateFeatureRequestRequest) Get() *CreateFeatureRequestRequest {
	return v.value
}

func (v *NullableCreateFeatureRequestRequest) Set(val *CreateFeatureRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFeatureRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFeatureRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFeatureRequestRequest(val *CreateFeatureRequestRequest) *NullableCreateFeatureRequestRequest {
	return &NullableCreateFeatureRequestRequest{value: val, isSet: true}
}

func (v NullableCreateFeatureRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFeatureRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


